import { MakeLogicType, actions, kea, listeners, path, reducers } from 'kea'
import { getRouterContext } from 'kea-router/lib/router'

import {
    DEFAULT_OS_VARIANT,
    OS_VARIANT_STORAGE_KEY,
    OsVariantKey,
    isOsDesktopPath,
    resolveOsVariant,
} from './osVariants'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osVariantLogicValues {
    exploring: boolean
    variant: OsVariantKey
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osVariantLogicActions {
    leavePreview: () => {
        value: true
    }
    setVariant: (variant: OsVariantKey) => {
        variant: OsVariantKey
    }
}

export type osVariantLogicType = MakeLogicType<osVariantLogicValues, osVariantLogicActions, Record<string, any>>

function readStored(): string | null {
    try {
        return sessionStorage.getItem(OS_VARIANT_STORAGE_KEY)
    } catch {
        return null
    }
}

function writeStored(variant: OsVariantKey | null): void {
    try {
        if (variant) {
            sessionStorage.setItem(OS_VARIANT_STORAGE_KEY, variant)
        } else {
            sessionStorage.removeItem(OS_VARIANT_STORAGE_KEY)
        }
    } catch {
        // Without sessionStorage the pick only lasts until the next reload.
    }
}

const initial = (): ReturnType<typeof resolveOsVariant> =>
    resolveOsVariant(window.location.pathname, window.location.search, readStored())

export const osVariantLogic = kea<osVariantLogicType>([
    path(['scenes', 'os', 'variants', 'osVariantLogic']),
    actions({
        setVariant: (variant: OsVariantKey) => ({ variant }),
        leavePreview: true,
    }),
    reducers(() => {
        const choice = initial()
        if (choice.exploring) {
            writeStored(choice.variant)
        }
        return {
            variant: [
                choice.variant as OsVariantKey,
                { setVariant: (_, { variant }) => variant, leavePreview: () => DEFAULT_OS_VARIANT },
            ],
            exploring: [choice.exploring, { setVariant: () => true, leavePreview: () => false }],
        }
    }),
    listeners(() => ({
        setVariant: ({ variant }) => {
            writeStored(variant)
            // While no window has moved the address bar, it keeps a shareable `/os?variant=` link.
            if (isOsDesktopPath(window.location.pathname)) {
                const history = getRouterContext().history ?? window.history
                history.replaceState(window.history.state, '', `${window.location.pathname}?variant=${variant}`)
            }
        },
        leavePreview: () => writeStored(null),
    })),
])
