import { MakeLogicType, afterMount, connect, kea, listeners, path } from 'kea'

import { osWindowsLogic } from '../../windows/osWindowsLogic'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osTilingLogicActions {
    closeWindow: (id: string) => { id: string } // osWindowsLogic
    minimizeWindow: (id: string) => { id: string } // osWindowsLogic
    openWindow: (
        path: string,
        options?: import('../../windows/osWindowsLogic').OsOpenWindowOptions
    ) => { id: string; options: import('../../windows/osWindowsLogic').OsOpenWindowOptions; path: string } // osWindowsLogic
    restoreWindow: (id: string) => { id: string } // osWindowsLogic
    setDesktopSize: (desktop: import('../../windows/osWindowGeometry').OsSize) => {
        desktop: import('../../windows/osWindowGeometry').OsSize
    } // osWindowsLogic
    tidyUpWindows: () => { value: true } // osWindowsLogic
}

export type osTilingLogicType = MakeLogicType<Record<string, any>, osTilingLogicActions, Record<string, any>>

/** PROTOTYPE variant D: the visible windows always tile the desktop. A dragged window re-tiles on the next change. */
export const osTilingLogic = kea<osTilingLogicType>([
    path(['scenes', 'os', 'variants', 'tiling', 'osTilingLogic']),
    connect(() => ({
        actions: [
            osWindowsLogic,
            ['openWindow', 'closeWindow', 'minimizeWindow', 'restoreWindow', 'setDesktopSize', 'tidyUpWindows'],
        ],
    })),
    listeners(({ actions }) => ({
        openWindow: () => actions.tidyUpWindows(),
        closeWindow: () => actions.tidyUpWindows(),
        minimizeWindow: () => actions.tidyUpWindows(),
        restoreWindow: () => actions.tidyUpWindows(),
        setDesktopSize: () => actions.tidyUpWindows(),
    })),
    afterMount(({ actions }) => actions.tidyUpWindows()),
])
