import { MakeLogicType, actions, connect, kea, listeners, path, reducers, selectors } from 'kea'
import { actionToUrl, combineUrl, router, urlToAction } from 'kea-router'
import posthog from 'posthog-js'

import { FEATURE_FLAGS } from 'lib/constants'
import { FeatureFlagsSet, featureFlagLogic } from 'lib/logic/featureFlagLogic'
import { removeProjectIdIfPresent } from 'lib/utils/kea-router'
import {
    AI_COMPOSER_MODE_VALUE,
    EDITOR_MODE_PARAM,
    EDITOR_MODE_VALUE,
    aiComposerAvailable,
    isAiFirstVariant,
} from 'scenes/max/aiFirstCreate/aiFirstMode'
import { sceneAgentPanelLogic } from 'scenes/max/sceneAgentPanelLogic'
import { urls } from 'scenes/urls'

import type { HogFlowTemplate } from './hogflows/types'
import { parseFacetQuery } from './WorkflowsListV2/FacetSearchBar/facetQuery'
import { buildWorkflowListFacets } from './WorkflowsListV2/workflowListFacets'
import { TRIGGER_PREFILL_PARAM } from './workflowTriggerPrefill'

function newWorkflowFolderParams(
    searchParams: Record<string, unknown>,
    projectBrowser: boolean
): Record<string, string> {
    const carriedFolder = new URLSearchParams(router.values.location.search).get('_create_in_folder')
    if (!projectBrowser) {
        return {}
    }
    const folder =
        carriedFolder ??
        parseFacetQuery(typeof searchParams.q === 'string' ? searchParams.q : '', buildWorkflowListFacets([])).find(
            (filter) => filter.facet === 'in' && !filter.negated
        )?.value
    return folder ? { _create_in_folder: folder } : {}
}

/** The new-workflow URL for an entry that means "start from nothing", the only kind the composer answers. */
export function urlForNewWorkflowComposer(): string {
    return combineUrl(urls.workflowNew(), { [EDITOR_MODE_PARAM]: AI_COMPOSER_MODE_VALUE }).url
}

// The editor scene is `/workflows/:id/:tab`, and only the `new` id can show the composer.
function isNewWorkflowRoute(pathname: string): boolean {
    const [, section, id] = removeProjectIdIfPresent(pathname).split('/')
    return section === 'workflows' && id === 'new'
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface newWorkflowLogicValues {
    featureFlags: FeatureFlagsSet // featureFlagLogic
    location: {
        pathname: string
        search: string
        hash: string
    } // router
    searchParams: Record<string, any> // router
    sceneIntegrationEnabled: boolean // sceneAgentPanelLogic
    aiComposerAvailable: boolean
    aiFirstNewEnabled: boolean
    newWorkflowModalVisible: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface newWorkflowLogicActions {
    createEmptyWorkflow: () => {
        value: true
    }
    createWorkflowFromTemplate: (template: HogFlowTemplate) => {
        template: HogFlowTemplate
    }
    hideNewWorkflowModal: () => {
        value: true
    }
    openEditorFromAiComposer: () => {
        value: true
    }
    showNewWorkflowModal: () => {
        value: true
    }
    startNewWorkflow: () => {
        value: true
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface newWorkflowLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        aiFirstNewEnabled: (featureFlags: FeatureFlagsSet, sceneIntegrationEnabled: boolean) => boolean
        aiComposerAvailable: (
            featureFlags: FeatureFlagsSet,
            sceneIntegrationEnabled: boolean,
            searchParams: Record<string, any>,
            location: {
                hash: string
                pathname: string
                search: string
            }
        ) => boolean
    }
}

export type newWorkflowLogicType = MakeLogicType<
    newWorkflowLogicValues,
    newWorkflowLogicActions,
    Record<string, any>,
    newWorkflowLogicMeta
>

export const newWorkflowLogic = kea<newWorkflowLogicType>([
    path(['products', 'workflows', 'frontend', 'newWorkflowLogic']),
    connect(() => ({
        values: [
            featureFlagLogic,
            ['featureFlags'],
            sceneAgentPanelLogic,
            ['sceneIntegrationEnabled'],
            router,
            ['searchParams', 'location'],
        ],
    })),
    actions({
        startNewWorkflow: true,
        showNewWorkflowModal: true,
        hideNewWorkflowModal: true,
        openEditorFromAiComposer: true,
        createWorkflowFromTemplate: (template: HogFlowTemplate) => ({ template }),
        createEmptyWorkflow: true,
    }),
    reducers({
        newWorkflowModalVisible: [
            false,
            {
                showNewWorkflowModal: () => true,
                hideNewWorkflowModal: () => false,
            },
        ],
    }),
    selectors({
        // Same gate as the scene integration. Only the `test` variant, or a plain boolean rollout, qualifies.
        aiFirstNewEnabled: [
            (s) => [s.featureFlags, s.sceneIntegrationEnabled],
            (featureFlags: FeatureFlagsSet, sceneIntegrationEnabled: boolean): boolean =>
                sceneIntegrationEnabled && isAiFirstVariant(FEATURE_FLAGS.WORKFLOWS_AI_FIRST_NEW, featureFlags),
        ],
        // Deep links with a starting point stay on the editor. Checked here so the scene never reads the flag early.
        aiComposerAvailable: [
            (s) => [s.featureFlags, s.sceneIntegrationEnabled, s.searchParams, s.location],
            (
                featureFlags: FeatureFlagsSet,
                sceneIntegrationEnabled: boolean,
                searchParams: Record<string, any>,
                location: { pathname: string }
            ): boolean =>
                aiComposerAvailable(
                    FEATURE_FLAGS.WORKFLOWS_AI_FIRST_NEW,
                    featureFlags,
                    sceneIntegrationEnabled,
                    searchParams,
                    isNewWorkflowRoute(location.pathname) &&
                        !searchParams.templateId &&
                        !searchParams.editTemplateId &&
                        !searchParams[TRIGGER_PREFILL_PARAM]
                ),
        ],
    }),
    listeners(({ actions, values }) => ({
        startNewWorkflow: () => {
            // Exposure is recorded at the click, and only when the composer could answer it.
            if (values.sceneIntegrationEnabled) {
                posthog.getFeatureFlag(FEATURE_FLAGS.WORKFLOWS_AI_FIRST_NEW)
            }
            if (values.aiFirstNewEnabled) {
                router.actions.push(urls.workflowNew(), {
                    ...newWorkflowFolderParams(
                        values.searchParams,
                        !!values.featureFlags[FEATURE_FLAGS.WORKFLOWS_LIST_V2] &&
                            !!values.featureFlags[FEATURE_FLAGS.WORKFLOWS_PROJECT_FILES]
                    ),
                    [EDITOR_MODE_PARAM]: AI_COMPOSER_MODE_VALUE,
                })
            } else {
                actions.showNewWorkflowModal()
            }
        },
        openEditorFromAiComposer: () => {
            actions.showNewWorkflowModal()
        },
        createWorkflowFromTemplate: ({ template }) => {
            const folderParams = newWorkflowFolderParams(
                values.searchParams,
                !!values.featureFlags[FEATURE_FLAGS.WORKFLOWS_LIST_V2] &&
                    !!values.featureFlags[FEATURE_FLAGS.WORKFLOWS_PROJECT_FILES]
            )
            actions.hideNewWorkflowModal()
            router.actions.push(urls.workflowNew(), {
                ...folderParams,
                templateId: template.id,
            })
        },
        createEmptyWorkflow: () => {
            const folderParams = newWorkflowFolderParams(
                values.searchParams,
                !!values.featureFlags[FEATURE_FLAGS.WORKFLOWS_LIST_V2] &&
                    !!values.featureFlags[FEATURE_FLAGS.WORKFLOWS_PROJECT_FILES]
            )
            actions.hideNewWorkflowModal()
            router.actions.push(urls.workflowNew(), {
                ...folderParams,
                ...(values.aiFirstNewEnabled ? { [EDITOR_MODE_PARAM]: EDITOR_MODE_VALUE } : {}),
            })
        },
    })),
    urlToAction(({ actions }) => ({
        '/workflows': (_, _searchParams, hashParams) => {
            if ('newWorkflow' in hashParams) {
                actions.showNewWorkflowModal()
            }
        },
        '/workflows/:tab': (_, _searchParams, hashParams) => {
            if ('newWorkflow' in hashParams) {
                actions.showNewWorkflowModal()
            }
        },
    })),
    actionToUrl({
        hideNewWorkflowModal: () => {
            const hashParams = { ...router.values.hashParams }
            delete hashParams['newWorkflow']
            return [router.values.location.pathname, router.values.searchParams, hashParams]
        },
        showNewWorkflowModal: () => {
            const hashParams = { ...router.values.hashParams }
            hashParams['newWorkflow'] = 'modal'
            return [router.values.location.pathname, router.values.searchParams, hashParams]
        },
    }),
])
