import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, reducers, selectors } from 'kea'
import { loaders } from 'kea-loaders'
import { router, urlToAction } from 'kea-router'

import { lemonToast } from '@posthog/lemon-ui'

import { ApiError } from 'lib/api-error'
import { FEATURE_FLAGS } from 'lib/constants'
import { featureFlagLogic, type FeatureFlagsSet } from 'lib/logic/featureFlagLogic'
import { getAccessControlDisabledReason } from 'lib/utils/accessControlUtils'
import { teamLogic } from 'scenes/teamLogic'
import { urls } from 'scenes/urls'
import { userLogic } from 'scenes/userLogic'

import { AccessControlLevel, AccessControlResourceType, type UserType } from '~/types'

import * as api from '../../generated/api'
import type { WorkflowViewApi } from '../../generated/api.schemas'
import { FacetSearchValue, createFacetMatcher, parseFacetQuery, serializeFacetQuery } from './FacetSearchBar/facetQuery'
import type { FacetDefinition, MatchesText } from './FacetSearchBar/facetQuery'
import { DEFAULT_COLUMNS } from './workflowListLabels'
import type { OptionalColumn } from './workflowListLabels'
import type { WorkflowLibraryRow } from './workflowListRows'
import {
    BUILT_IN_WORKFLOW_VIEWS,
    WorkflowSavedView,
    normalizeViewColumns,
    savedViewChanges,
    workflowViewState,
    workflowViewValue,
} from './workflowSavedViews'
import { workflowsListV2Logic, type ServerSearchResult } from './workflowsListV2Logic'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface workflowsSavedViewsLogicValues {
    featureFlags: FeatureFlagsSet // featureFlagLogic
    receivedFeatureFlags: boolean // featureFlagLogic
    user: UserType | null // userLogic
    currentTeamId: number | null // workflowsListV2Logic
    facets: FacetDefinition<WorkflowLibraryRow>[] // workflowsListV2Logic
    matchesText: MatchesText<WorkflowLibraryRow> // workflowsListV2Logic
    metricsLoaded: boolean // workflowsListV2Logic
    rows: WorkflowLibraryRow[] // workflowsListV2Logic
    serverSearch: ServerSearchResult | null // workflowsListV2Logic
    shownColumns: OptionalColumn[] // workflowsListV2Logic
    value: FacetSearchValue // workflowsListV2Logic
    activeView: WorkflowSavedView
    activeViewChanges: string[]
    activeViewId: string
    available: boolean
    canUpdateActiveView: boolean
    conflictedViewId: string | null
    defaultView: WorkflowViewApi | null
    enabled: boolean
    isModified: boolean
    myWorkflowsDeleted: boolean
    savedViews: WorkflowViewApi[] | null
    savedViewsLoadFailed: boolean
    savedViewsLoading: boolean
    saving: boolean
    sharedSaveDisabledReason: string | undefined
    viewCounts: Record<string, number>
    views: WorkflowSavedView[]
    writeDisabledReason: string | undefined
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface workflowsSavedViewsLogicActions {
    setFeatureFlags: (
        flags: string[],
        variants: Record<string, boolean | string>
    ) => {
        flags: string[]
        variants: Record<string, boolean | string>
    } // featureFlagLogic
    loadCurrentTeamSuccess: (
        currentTeam: null | import('~/types').TeamPublicType,
        payload?: any
    ) => {
        currentTeam: null | import('~/types').TeamPublicType
        payload?: any
    } // teamLogic
    clearFilters: () => {
        value: true
    } // workflowsListV2Logic
    resetColumns: () => {
        value: true
    } // workflowsListV2Logic
    setValue: (
        value: FacetSearchValue,
        fromUrl?: boolean | undefined
    ) => {
        fromUrl: boolean
        value: FacetSearchValue
    } // workflowsListV2Logic
    setVisibleColumns: (columns: ('created_by' | 'health' | 'last_7_days' | 'owner' | 'trigger' | 'type')[]) => {
        columns: ('created_by' | 'health' | 'last_7_days' | 'owner' | 'trigger' | 'type')[]
    } // workflowsListV2Logic
    toggleColumn: (column: 'created_by' | 'health' | 'last_7_days' | 'owner' | 'trigger' | 'type') => {
        column: 'created_by' | 'health' | 'last_7_days' | 'owner' | 'trigger' | 'type'
    } // workflowsListV2Logic
    applyView: (view: WorkflowSavedView) => {
        view: WorkflowSavedView
    }
    clearSavedViews: () => {
        value: true
    }
    deleteView: (id: string) => {
        id: string
    }
    loadSavedViews: () => {
        value: true
    }
    loadSavedViewsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadSavedViewsSuccess: (
        savedViews: WorkflowViewApi[] | null,
        payload?: {
            value: true
        }
    ) => {
        savedViews: WorkflowViewApi[] | null
        payload?: {
            value: true
        }
    }
    removeSavedView: (id: string) => {
        id: string
    }
    renameView: (
        id: string,
        name: string
    ) => {
        id: string
        name: string
    }
    resetView: () => {
        value: true
    }
    restoreMyWorkflows: () => {
        value: true
    }
    saveViewAs: (name: string) => {
        name: string
    }
    setActiveViewId: (id: string) => {
        id: string
    }
    setConflictedViewId: (id: string | null) => {
        id: string | null
    }
    setDefaultView: (view: WorkflowViewApi | null) => {
        view: WorkflowViewApi | null
    }
    setSavedViewsLoadFailed: (failed: boolean) => {
        failed: boolean
    }
    setSaving: (saving: boolean) => {
        saving: boolean
    }
    syncViewFromUrl: () => {
        value: true
    }
    updateActiveView: () => {
        value: true
    }
    upsertSavedView: (view: WorkflowViewApi) => {
        view: WorkflowViewApi
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface workflowsSavedViewsLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        enabled: (featureFlags: FeatureFlagsSet, receivedFeatureFlags: boolean) => boolean
        available: (enabled: boolean, savedViews: WorkflowViewApi[] | null) => boolean
        writeDisabledReason: (currentTeamId: number | null, user: UserType | null) => string | undefined
        views: (savedViews: WorkflowViewApi[] | null) => WorkflowSavedView[]
        activeView: (views: WorkflowSavedView[], activeViewId: string) => WorkflowSavedView
        activeViewChanges: (
            activeView: WorkflowSavedView,
            value: FacetSearchValue,
            shownColumns: ('created_by' | 'health' | 'last_7_days' | 'owner' | 'trigger' | 'type')[]
        ) => string[]
        isModified: (activeViewChanges: string[]) => boolean
        canUpdateActiveView: (activeView: WorkflowSavedView) => boolean
        sharedSaveDisabledReason: (conflictedViewId: string | null, activeViewId: string) => string | undefined
        myWorkflowsDeleted: (defaultView: WorkflowViewApi | null) => boolean
        viewCounts: (
            views: WorkflowSavedView[],
            rows: WorkflowLibraryRow[],
            facets: FacetDefinition<WorkflowLibraryRow>[],
            matchesText: MatchesText<WorkflowLibraryRow>,
            serverSearch: ServerSearchResult | null,
            metricsLoaded: boolean
        ) => Record<string, number>
    }
}

export type workflowsSavedViewsLogicType = MakeLogicType<
    workflowsSavedViewsLogicValues,
    workflowsSavedViewsLogicActions,
    Record<string, any>,
    workflowsSavedViewsLogicMeta
>

export const workflowsSavedViewsLogic = kea<workflowsSavedViewsLogicType>([
    path(['products', 'workflows', 'frontend', 'Workflows', 'WorkflowsListV2', 'workflowsSavedViewsLogic']),
    connect(() => ({
        values: [
            featureFlagLogic,
            ['featureFlags', 'receivedFeatureFlags'],
            workflowsListV2Logic,
            [
                'currentTeamId',
                'value',
                'shownColumns',
                'rows',
                'facets',
                'matchesText',
                'serverSearch',
                'metricsLoaded',
            ],
            userLogic,
            ['user'],
        ],
        actions: [
            featureFlagLogic,
            ['setFeatureFlags'],
            teamLogic,
            ['loadCurrentTeamSuccess'],
            workflowsListV2Logic,
            ['setValue', 'clearFilters', 'setVisibleColumns', 'toggleColumn', 'resetColumns'],
        ],
    })),
    actions({
        setSavedViewsLoadFailed: (failed: boolean) => ({ failed }),
        loadSavedViews: true,
        setActiveViewId: (id: string) => ({ id }),
        applyView: (view: WorkflowSavedView) => ({ view }),
        resetView: true,
        saveViewAs: (name: string) => ({ name }),
        updateActiveView: true,
        renameView: (id: string, name: string) => ({ id, name }),
        deleteView: (id: string) => ({ id }),
        restoreMyWorkflows: true,
        upsertSavedView: (view: WorkflowViewApi) => ({ view }),
        removeSavedView: (id: string) => ({ id }),
        setDefaultView: (view: WorkflowViewApi | null) => ({ view }),
        setSaving: (saving: boolean) => ({ saving }),
        setConflictedViewId: (id: string | null) => ({ id }),
        syncViewFromUrl: true,
        clearSavedViews: true,
    }),
    loaders(({ values, actions }) => ({
        savedViews: [
            null as WorkflowViewApi[] | null,
            {
                loadSavedViews: async (_, breakpoint) => {
                    if (!values.enabled || values.currentTeamId === null) {
                        return null
                    }
                    try {
                        const all: WorkflowViewApi[] = []
                        let offset = 0
                        for (let pageIndex = 0; pageIndex < 40; pageIndex++) {
                            const page = await api.workflowViewsList(String(values.currentTeamId), {
                                limit: 100,
                                offset,
                            })
                            breakpoint()
                            if (!values.enabled) {
                                return null
                            }
                            all.push(...page.results)
                            if (!page.next) {
                                const defaultView = all.find((view) => view.default_key === 'my-workflows')
                                if (defaultView) {
                                    actions.setDefaultView(defaultView)
                                } else {
                                    try {
                                        const initialized = await api.workflowViewsInitializeCreate(
                                            String(values.currentTeamId)
                                        )
                                        breakpoint()
                                        if (!values.enabled) {
                                            return null
                                        }
                                        actions.setDefaultView(initialized)
                                        if (!initialized.deleted) {
                                            all.unshift(initialized)
                                        }
                                    } catch (error) {
                                        breakpoint()
                                        if (!(error instanceof ApiError) || error.status !== 403) {
                                            throw error
                                        }
                                    }
                                }
                                return all
                            }
                            const nextOffset = Number(
                                new URL(page.next, window.location.origin).searchParams.get('offset')
                            )
                            if (nextOffset <= offset || !page.results.length) {
                                throw new Error('Saved views pagination did not advance')
                            }
                            offset = nextOffset
                        }
                        throw new Error('Too many saved views pages')
                    } catch {
                        breakpoint()
                        actions.setSavedViewsLoadFailed(true)
                        return null
                    }
                },
            },
        ],
    })),
    reducers({
        savedViewsLoadFailed: [
            false,
            {
                setSavedViewsLoadFailed: (_, { failed }) => failed,
                loadSavedViews: () => false,
                clearSavedViews: () => false,
            },
        ],
        activeViewId: [
            'all',
            { setActiveViewId: (_, { id }) => id, applyView: (_, { view }) => view.id, clearSavedViews: () => 'all' },
        ],
        saving: [false, { setSaving: (_, { saving }) => saving }],
        conflictedViewId: [
            null as string | null,
            { setConflictedViewId: (_, { id }) => id, clearSavedViews: () => null },
        ],
        defaultView: [
            null as WorkflowViewApi | null,
            { setDefaultView: (_, { view }) => view, clearSavedViews: () => null },
        ],
        savedViews: {
            clearSavedViews: () => null,
            upsertSavedView: (state, { view }) =>
                state &&
                (state.some((candidate) => candidate.id === view.id)
                    ? state.map((candidate) => (candidate.id === view.id ? view : candidate))
                    : [...state, view]),
            removeSavedView: (state, { id }) => state && state.filter((view) => view.id !== id),
        },
    }),
    selectors({
        enabled: [
            (s) => [s.featureFlags, s.receivedFeatureFlags],
            (featureFlags: FeatureFlagsSet, receivedFeatureFlags: boolean): boolean =>
                receivedFeatureFlags &&
                featureFlags[FEATURE_FLAGS.WORKFLOWS_LIST_V2] === true &&
                featureFlags[FEATURE_FLAGS.WORKFLOWS_SAVED_VIEWS] === true,
        ],
        available: [
            (s) => [s.enabled, s.savedViews],
            (enabled: boolean, savedViews: WorkflowViewApi[] | null): boolean => enabled && savedViews !== null,
        ],
        writeDisabledReason: [
            (s) => [s.currentTeamId, s.user],
            (): string | undefined =>
                getAccessControlDisabledReason(AccessControlResourceType.Workflow, AccessControlLevel.Editor) ??
                undefined,
        ],
        views: [
            (s) => [s.savedViews],
            (savedViews: WorkflowViewApi[] | null): WorkflowSavedView[] => [
                BUILT_IN_WORKFLOW_VIEWS[0],
                ...(savedViews ?? []).filter((view) => view.default_key === 'my-workflows'),
                ...BUILT_IN_WORKFLOW_VIEWS.slice(1),
                ...(savedViews ?? []).filter((view) => view.default_key !== 'my-workflows'),
            ],
        ],
        activeView: [
            (s) => [s.views, s.activeViewId],
            (views: WorkflowSavedView[], activeViewId: string): WorkflowSavedView =>
                views.find((view) => view.id === activeViewId) ?? BUILT_IN_WORKFLOW_VIEWS[0],
        ],
        activeViewChanges: [
            (s) => [s.activeView, s.value, s.shownColumns],
            (view: WorkflowSavedView, value: FacetSearchValue, columns: OptionalColumn[]): string[] =>
                savedViewChanges(view, value, columns),
        ],
        isModified: [(s) => [s.activeViewChanges], (changes: string[]): boolean => changes.length > 0],
        canUpdateActiveView: [(s) => [s.activeView], (view: WorkflowSavedView): boolean => !view.builtIn],
        sharedSaveDisabledReason: [
            (s) => [s.conflictedViewId, s.activeViewId],
            (conflictedViewId: string | null, activeViewId: string): string | undefined =>
                conflictedViewId === activeViewId ? 'Reset to the latest view before saving for everyone' : undefined,
        ],
        myWorkflowsDeleted: [(s) => [s.defaultView], (view: WorkflowViewApi | null): boolean => view?.deleted === true],
        viewCounts: [
            (s) => [s.views, s.rows, s.facets, s.matchesText, s.serverSearch, s.metricsLoaded],
            (
                views: WorkflowSavedView[],
                rows: WorkflowLibraryRow[],
                facets: FacetDefinition<WorkflowLibraryRow>[],
                matchesText: MatchesText<WorkflowLibraryRow>,
                serverSearch: ServerSearchResult | null,
                metricsLoaded: boolean
            ): Record<string, number> =>
                Object.fromEntries(
                    views.flatMap((view) => {
                        if (!metricsLoaded && view.state.filters.some((filter) => filter.facet === 'health')) {
                            return []
                        }
                        const text = view.state.text.trim()
                        if (text.length >= 3 && (serverSearch?.text !== text || serverSearch.failed)) {
                            return []
                        }
                        const value = workflowViewValue(view.state)
                        return [[view.id, rows.filter(createFacetMatcher(value, facets, matchesText)).length]]
                    })
                ),
        ],
    }),
    listeners(({ actions, values, cache }) => {
        const writeUrl = (): void => {
            if (!values.available || cache.applyingView || cache.syncingUrl) {
                return
            }
            const next = {
                ...router.values.searchParams,
                view: values.activeViewId,
                q: serializeFacetQuery(values.value.filters),
                text: values.value.text.trim(),
                columns: values.shownColumns.join(','),
            }
            const raw = new URLSearchParams(router.values.location.search)
            if (
                raw.get('view') === next.view &&
                raw.get('q') === next.q &&
                raw.get('text') === next.text &&
                raw.get('columns') === next.columns
            ) {
                return
            }
            cache.writingUrl = true
            router.actions.replace(router.values.location.pathname, next, router.values.hashParams)
            cache.writingUrl = false
        }
        const runMutation = async (
            run: (stillCurrent: () => boolean) => Promise<void>,
            rethrow = false,
            permission: 'read' | 'write' = 'write'
        ): Promise<void> => {
            if (!values.available || values.saving || (permission === 'write' && values.writeDisabledReason)) {
                return
            }
            actions.setSaving(true)
            const teamId = values.currentTeamId
            const viewId = values.activeViewId
            const generation = cache.contextGeneration ?? 0
            const stillCurrent = (): boolean =>
                values.enabled && values.currentTeamId === teamId && (cache.contextGeneration ?? 0) === generation
            try {
                await run(stillCurrent)
            } catch (error) {
                if (!stillCurrent()) {
                    return
                }
                if (error instanceof ApiError && error.status === 409) {
                    actions.setConflictedViewId(viewId)
                    lemonToast.error(
                        'This view changed since you opened it. Your changes are still here. Save as a new view or reset to the latest version.'
                    )
                } else {
                    lemonToast.error("Couldn't save your changes. Check your connection and try again.")
                }
                if (rethrow) {
                    throw error
                }
            } finally {
                actions.setSaving(false)
            }
        }
        return {
            clearSavedViews: () => {
                cache.contextGeneration = (cache.contextGeneration ?? 0) + 1
            },
            setFeatureFlags: () => {
                if (!values.enabled) {
                    actions.clearSavedViews()
                    actions.loadSavedViews()
                } else if (values.savedViews === null && !values.savedViewsLoading) {
                    actions.loadSavedViews()
                }
            },
            loadCurrentTeamSuccess: ({ currentTeam }) => {
                if (cache.loadedTeamId !== currentTeam?.id) {
                    cache.loadedTeamId = currentTeam?.id
                    actions.clearSavedViews()
                    actions.loadSavedViews()
                }
            },
            loadSavedViewsSuccess: () => actions.syncViewFromUrl(),
            setValue: ({ fromUrl }) => {
                if (!fromUrl) {
                    writeUrl()
                }
            },
            setActiveViewId: writeUrl,
            clearFilters: writeUrl,
            setVisibleColumns: writeUrl,
            toggleColumn: writeUrl,
            resetColumns: writeUrl,
            applyView: ({ view }) => {
                if (!values.available) {
                    return
                }
                if (values.conflictedViewId === view.id) {
                    actions.resetView()
                    return
                }
                cache.applyingView = true
                actions.setValue(workflowViewValue(view.state))
                actions.setVisibleColumns(normalizeViewColumns(view.state.columns))
                cache.applyingView = false
                writeUrl()
            },
            resetView: async () => {
                if (!values.available || values.saving) {
                    return
                }
                if (values.conflictedViewId === values.activeViewId) {
                    const currentViewId = values.activeViewId
                    await runMutation(
                        async (stillCurrent) => {
                            try {
                                const latest = await api.workflowViewsRetrieve(
                                    String(values.currentTeamId),
                                    currentViewId
                                )
                                if (!stillCurrent()) {
                                    return
                                }
                                actions.upsertSavedView(latest)
                                actions.setConflictedViewId(null)
                                if (values.activeViewId === currentViewId) {
                                    actions.applyView(latest)
                                }
                            } catch (error) {
                                if (!(error instanceof ApiError) || error.status !== 404) {
                                    throw error
                                }
                                if (!stillCurrent()) {
                                    return
                                }
                                actions.removeSavedView(currentViewId)
                                if (values.activeViewId === currentViewId) {
                                    actions.applyView(BUILT_IN_WORKFLOW_VIEWS[0])
                                }
                            }
                            actions.setConflictedViewId(null)
                        },
                        false,
                        'read'
                    )
                } else {
                    actions.applyView(values.activeView)
                }
            },
            syncViewFromUrl: () => {
                if (!values.available || cache.writingUrl || cache.applyingView) {
                    return
                }
                const raw = new URLSearchParams(router.values.location.search)
                const id = raw.get('view') ?? 'all'
                const view = values.views.find((candidate) => candidate.id === id)
                const explicit = raw.has('q') || raw.has('text') || raw.has('columns')
                if (view && !explicit) {
                    actions.applyView(view)
                    return
                }
                cache.syncingUrl = true
                actions.setActiveViewId(view?.id ?? 'all')
                if (explicit) {
                    const value: FacetSearchValue = {
                        filters: raw.has('q')
                            ? parseFacetQuery(raw.get('q') ?? '', values.facets)
                            : view
                              ? workflowViewValue(view.state).filters
                              : [],
                        text: raw.has('text') ? (raw.get('text') ?? '') : (view?.state.text ?? ''),
                    }
                    actions.setValue(value)
                    actions.setVisibleColumns(
                        normalizeViewColumns(
                            raw.has('columns')
                                ? (raw.get('columns') ?? '').split(',')
                                : (view?.state.columns ?? DEFAULT_COLUMNS)
                        )
                    )
                }
                cache.syncingUrl = false
                if (!view && id !== 'all') {
                    if (!explicit) {
                        actions.applyView(BUILT_IN_WORKFLOW_VIEWS[0])
                    } else {
                        writeUrl()
                    }
                }
            },
            saveViewAs: async ({ name }) =>
                await runMutation(async (stillCurrent) => {
                    const sourceViewId = values.activeViewId
                    const view = await api.workflowViewsCreate(String(values.currentTeamId), {
                        name: name.trim(),
                        state: workflowViewState(values.value, values.shownColumns),
                    })
                    if (!stillCurrent()) {
                        return
                    }
                    actions.upsertSavedView(view)
                    if (values.activeViewId === sourceViewId) {
                        actions.setActiveViewId(view.id)
                    }
                    lemonToast.success(`Saved ${view.name} as a new view`)
                }, true),
            updateActiveView: async () =>
                await runMutation(async (stillCurrent) => {
                    const current = values.activeView
                    if (current.builtIn || values.sharedSaveDisabledReason) {
                        return
                    }
                    const view = await api.workflowViewsPartialUpdate(String(values.currentTeamId), current.id, {
                        version: current.version,
                        state: workflowViewState(values.value, values.shownColumns),
                    })
                    if (!stillCurrent()) {
                        return
                    }
                    actions.upsertSavedView(view)
                    lemonToast.success(`Saved ${view.name} for everyone`)
                }),
            renameView: async ({ id, name }) =>
                await runMutation(async (stillCurrent) => {
                    const current = values.views.find((view) => view.id === id)
                    if (!current || current.builtIn) {
                        return
                    }
                    const updated = await api.workflowViewsPartialUpdate(String(values.currentTeamId), id, {
                        version: current.version,
                        name: name.trim(),
                    })
                    if (!stillCurrent()) {
                        return
                    }
                    actions.upsertSavedView(updated)
                }, true),
            deleteView: async ({ id }) =>
                await runMutation(async (stillCurrent) => {
                    const current = values.views.find((view) => view.id === id)
                    if (!current || current.builtIn) {
                        return
                    }
                    await api.workflowViewsDestroy(String(values.currentTeamId), id, { version: current.version })
                    if (!stillCurrent()) {
                        return
                    }
                    actions.removeSavedView(id)
                    if (values.activeViewId === id) {
                        actions.applyView(BUILT_IN_WORKFLOW_VIEWS[0])
                    }
                    if (current.default_key === 'my-workflows') {
                        actions.setDefaultView({ ...values.defaultView!, deleted: true })
                        lemonToast.success('Deleted My workflows for everyone', {
                            button: { label: 'Undo', action: () => actions.restoreMyWorkflows() },
                        })
                    }
                }),
            restoreMyWorkflows: async () =>
                await runMutation(async (stillCurrent) => {
                    const view = await api.workflowViewsRestoreDefaultCreate(String(values.currentTeamId))
                    if (!stillCurrent()) {
                        return
                    }
                    actions.upsertSavedView(view)
                    actions.setDefaultView(view)
                    lemonToast.success('Restored My workflows for everyone')
                }),
        }
    }),
    urlToAction(({ actions }) => ({ [urls.workflows()]: () => actions.syncViewFromUrl() })),
    afterMount(({ actions, values, cache }) => {
        cache.loadedTeamId = values.currentTeamId
        actions.loadSavedViews()
    }),
])
