import { MakeLogicType, actions, connect, kea, listeners, path, reducers, selectors } from 'kea'

import { lemonToast } from '@posthog/lemon-ui'

import { moveToLogic } from 'lib/components/FileSystem/MoveTo/moveToLogic'

import { projectTreeDataLogic } from '~/layout/panel-layout/ProjectTree/projectTreeDataLogic'
import type { FileSystemEntry } from '~/queries/schema/schema-general'

import type { FacetSearchValue } from './FacetSearchBar/facetQuery'
import { workflowsListV2Logic } from './workflowsListV2Logic'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface workflowFoldersLogicValues {
    itemsByRef: Record<string, FileSystemEntry> // projectTreeDataLogic
    value: FacetSearchValue // workflowsListV2Logic
    currentFolder: string | null
    movingWorkflowId: string | null
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface workflowFoldersLogicActions {
    setValue: (value: FacetSearchValue) => {
        value: FacetSearchValue
    } // workflowsListV2Logic
    moveWorkflowToFolder: (id: string) => {
        id: string
    }
    openFolder: (folder: string | null) => {
        folder: string | null
    }
    setMovingWorkflowId: (id: string | null) => {
        id: string | null
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface workflowFoldersLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        currentFolder: (value: FacetSearchValue) => string | null
    }
}

export type workflowFoldersLogicType = MakeLogicType<
    workflowFoldersLogicValues,
    workflowFoldersLogicActions,
    Record<string, any>,
    workflowFoldersLogicMeta
>

export const workflowFoldersLogic = kea<workflowFoldersLogicType>([
    path(['products', 'workflows', 'frontend', 'workflowFoldersLogic']),
    connect({
        values: [workflowsListV2Logic, ['value'], projectTreeDataLogic, ['itemsByRef']],
        actions: [workflowsListV2Logic, ['setValue']],
    }),
    actions({
        openFolder: (folder: string | null) => ({ folder }),
        moveWorkflowToFolder: (id: string) => ({ id }),
        setMovingWorkflowId: (id: string | null) => ({ id }),
    }),
    reducers({
        movingWorkflowId: [null as string | null, { setMovingWorkflowId: (_, { id }) => id }],
    }),
    selectors({
        currentFolder: [
            (s) => [s.value],
            (value: FacetSearchValue): string | null =>
                value.filters.find((filter) => filter.facet === 'in' && !filter.negated)?.value ?? null,
        ],
    }),
    listeners(({ actions, values }) => ({
        openFolder: ({ folder }) => {
            actions.setValue({
                ...values.value,
                filters: [
                    ...values.value.filters.filter((filter) => filter.facet !== 'in'),
                    ...(folder === null ? [] : [{ facet: 'in', value: folder, negated: false }]),
                ],
            })
        },
        moveWorkflowToFolder: async ({ id }) => {
            if (values.movingWorkflowId) {
                return
            }
            actions.setMovingWorkflowId(id)
            try {
                await projectTreeDataLogic.asyncActions.syncTypeAndRef('hog_flow', id)
                const entry = values.itemsByRef[`hog_flow::${id}`]
                if (entry && !entry.shortcut) {
                    moveToLogic.actions.openMoveToModal([entry])
                } else {
                    lemonToast.error("Couldn't find this workflow in project files")
                }
            } catch {
                lemonToast.error("Couldn't load this workflow's folder")
            } finally {
                actions.setMovingWorkflowId(null)
            }
        },
    })),
])
