import { MakeLogicType, afterMount, beforeUnmount, connect, kea, path, props, propsChanged } from 'kea'

import { navPanelProductPushWelcomeLogic } from 'lib/components/NavPanelAdvertisement/navPanelProductPushWelcomeLogic'
import type { ProductSetupStatus } from 'lib/components/ProductEmptyState/types'

const WELCOME_HOLDER = 'workflows-first-run'

export interface FirstRunWelcomeHoldLogicProps {
    setupStatus: ProductSetupStatus
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface firstRunWelcomeHoldLogicActions {
    holdWelcome: (holder: string) => {
        holder: string
    } // navPanelProductPushWelcomeLogic
    releaseWelcome: (holder: string) => {
        holder: string
    } // navPanelProductPushWelcomeLogic
}

export type firstRunWelcomeHoldLogicType = MakeLogicType<
    {},
    firstRunWelcomeHoldLogicActions,
    FirstRunWelcomeHoldLogicProps
>

function updateWelcomeHold({ actions, props }: firstRunWelcomeHoldLogicType): void {
    if (props.setupStatus === 'loading' || props.setupStatus === 'needs-setup') {
        actions.holdWelcome(WELCOME_HOLDER)
    } else {
        actions.releaseWelcome(WELCOME_HOLDER)
    }
}

export const firstRunWelcomeHoldLogic = kea<firstRunWelcomeHoldLogicType>([
    props({} as FirstRunWelcomeHoldLogicProps),
    path(['products', 'workflows', 'frontend', 'firstRun', 'firstRunWelcomeHoldLogic']),
    connect(() => ({
        actions: [navPanelProductPushWelcomeLogic, ['holdWelcome', 'releaseWelcome']],
    })),
    afterMount(updateWelcomeHold),
    propsChanged(updateWelcomeHold),
    beforeUnmount(({ actions }) => {
        actions.releaseWelcome(WELCOME_HOLDER)
    }),
])
