const { chromium } = require('/home/coder/posthog/.claude/worktrees/agent-a1975d109b8af80be/node_modules/playwright')
const creds = require('/home/coder/dev/os-shell-stack/credentials.json')
const BASE = 'http://localhost:8105'
;(async () => {
    const browser = await chromium.launch()
    const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } })
    await ctx.request.post(BASE + '/api/login/', { data: { email: creds.email, password: creds.password } })
    const page = await ctx.newPage()
    await page.goto(`${BASE}/project/${creds.team_id}/insights`)
    await page.waitForSelector('.SceneTitleSection, h1', { timeout: 120000 })
    await page.waitForTimeout(3000)
    const osMenuBar = await page.locator('[data-attr="os-menu-bar"]').count()
    const iframes = await page.locator('[data-attr="os-window"] iframe').count()
    await page.screenshot({ path: '/tmp/os135/shots/flag-off-insights-1280.png' })
    await page.keyboard.press('Control+k')
    await page.waitForTimeout(1200)
    await page.screenshot({ path: '/tmp/os135/shots/flag-off-cmd-k-1280.png' })
    await page.goto(`${BASE}/project/${creds.team_id}/os`)
    await page.waitForTimeout(6000)
    const osPageText = (await page.locator('body').innerText()).slice(0, 300)
    await page.screenshot({ path: '/tmp/os135/shots/flag-off-os-route-1280.png' })
    console.log(JSON.stringify({ osMenuBar, iframes, osPageText }, null, 1))
    await browser.close()
})()
