import { MakeLogicType, actions, connect, kea, path, reducers, selectors } from 'kea'
import { actionToUrl, urlToAction } from 'kea-router'

import { Scene } from 'scenes/sceneTypes'
import { urls } from 'scenes/urls'

import { Breadcrumb } from '~/types'

import { audienceLogic } from './audienceLogic'

// pinned: URL path segments under /audience
export const AUDIENCE_TABS = ['recipients', 'engagement', 'topics', 'suppression', 'setup'] as const
export type AudienceTab = (typeof AUDIENCE_TABS)[number]

const TAB_LABELS: Record<AudienceTab, string> = {
    recipients: 'Recipients',
    engagement: 'Engagement',
    topics: 'Topics',
    suppression: 'Suppression list',
    setup: 'Set up',
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface audienceSceneLogicValues {
    selectedEmail: string | null // audienceLogic
    breadcrumbs: Breadcrumb[]
    currentTab: AudienceTab
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface audienceSceneLogicActions {
    setSelectedEmail: (email: string | null) => {
        email: string | null
    } // audienceLogic
    trackRecipientOpened: (email: string) => {
        email: string
    } // audienceLogic
    closeRecipient: () => {
        value: true
    }
    openRecipient: (email: string) => {
        email: string
    }
    setCurrentTab: (tab: AudienceTab) => {
        tab: 'engagement' | 'recipients' | 'setup' | 'suppression' | 'topics'
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface audienceSceneLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        breadcrumbs: (
            currentTab: 'engagement' | 'recipients' | 'setup' | 'suppression' | 'topics',
            selectedEmail: string | null
        ) => Breadcrumb[]
    }
}

export type audienceSceneLogicType = MakeLogicType<
    audienceSceneLogicValues,
    audienceSceneLogicActions,
    Record<string, any>,
    audienceSceneLogicMeta
>

export const audienceSceneLogic = kea<audienceSceneLogicType>([
    path(['products', 'workflows', 'frontend', 'Audience', 'audienceSceneLogic']),
    connect(() => ({
        actions: [audienceLogic, ['setSelectedEmail', 'trackRecipientOpened']],
        values: [audienceLogic, ['selectedEmail']],
    })),
    actions({
        setCurrentTab: (tab: AudienceTab) => ({ tab }),
        openRecipient: (email: string) => ({ email }),
        closeRecipient: true,
    }),
    reducers({
        currentTab: ['recipients' as AudienceTab, { setCurrentTab: (_, { tab }) => tab }],
    }),
    selectors({
        breadcrumbs: [
            (s) => [s.currentTab, s.selectedEmail],
            (
                currentTab: 'engagement' | 'recipients' | 'setup' | 'suppression' | 'topics',
                selectedEmail: string | null
            ): Breadcrumb[] => [
                { key: Scene.Audience, name: 'Audience', path: urls.audience(), iconType: 'workflows' },
                ...(selectedEmail
                    ? [
                          {
                              key: [Scene.Audience, 'recipients'] as [string, string],
                              name: 'Recipients',
                              path: urls.audience(),
                          },
                          { key: [Scene.Audience, selectedEmail] as [string, string], name: selectedEmail },
                      ]
                    : [{ key: [Scene.Audience, currentTab] as [string, string], name: TAB_LABELS[currentTab] }]),
            ],
        ],
    }),
    actionToUrl(() => ({
        setCurrentTab: ({ tab }) => urls.audience(tab),
        openRecipient: ({ email }) => urls.audienceRecipient(email),
        closeRecipient: () => urls.audience('recipients'),
    })),
    urlToAction(({ actions, values }) => ({
        [urls.audience()]: () => {
            actions.setSelectedEmail(null)
            if (values.currentTab !== 'recipients') {
                actions.setCurrentTab('recipients')
            }
        },
        [urls.audienceRecipient(':email')]: ({ email }) => {
            const decoded = email ? decodeURIComponent(email) : null
            if (values.currentTab !== 'recipients') {
                actions.setCurrentTab('recipients')
            }
            if (decoded !== values.selectedEmail) {
                actions.setSelectedEmail(decoded)
                if (decoded) {
                    actions.trackRecipientOpened(decoded)
                }
            }
        },
        [urls.audience(':tab' as AudienceTab)]: ({ tab }) => {
            const next: AudienceTab = AUDIENCE_TABS.includes(tab as AudienceTab) ? (tab as AudienceTab) : 'recipients'
            actions.setSelectedEmail(null)
            if (next !== values.currentTab) {
                actions.setCurrentTab(next)
            }
        },
    })),
])
