import { MakeLogicType, actions, afterMount, kea, listeners, path, reducers, selectors } from 'kea'
import { loaders } from 'kea-loaders'
import { router } from 'kea-router'
import posthog from 'posthog-js'

import api, { ApiConfig } from 'lib/api'
import { urls } from 'scenes/urls'

import { audienceEngagementDashboardTemplate } from './audienceEngagementQueries'
import { ALL_MARKETING_TOPIC_ID, EMPTY_AUDIENCE_FIXTURES, buildAudienceFixtures } from './audienceFixtures'
import type {
    AudienceEngagementEvent,
    AudienceFixtureData,
    AudienceRecipient,
    AudienceTopic,
    AudienceTopicStatus,
} from './audienceFixtures'

export type AudienceShowFilter = 'all' | 'suppressed' | 'no_preference' | 'unsubscribed_all' | 'no_person'

export interface AudienceTopicFilter {
    topicId: string
    status: AudienceTopicStatus
}

export interface AudienceGapCounts {
    personsWithoutEmail: number
    personsTotal: number
    recipientsWithoutPreference: number
    suppressed: number
    recipientsWithoutPerson: number
}

const RECIPIENTS_PAGE_SIZE = 50

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface audienceLogicValues {
    audience: AudienceFixtureData | null
    audienceLoading: boolean
    createdDashboard: {
        id: number
    } | null
    createdDashboardLoading: boolean
    filteredRecipients: AudienceRecipient[]
    gapCounts: AudienceGapCounts | null
    isSetupNeeded: boolean | null
    recipients: AudienceRecipient[]
    recipientsPageSize: number
    searchTerm: string
    selectedEmail: string | null
    selectedRecipient: AudienceRecipient | null
    selectedRecipientEvents: AudienceEngagementEvent[]
    showFilter: AudienceShowFilter
    topicFilter: AudienceTopicFilter | null
    topics: AudienceTopic[]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface audienceLogicActions {
    createDashboardFromTemplate: () => any
    createDashboardFromTemplateFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    createDashboardFromTemplateSuccess: (
        createdDashboard: {
            id: number
        },
        payload?: any
    ) => {
        createdDashboard: {
            id: number
        }
        payload?: any
    }
    loadAudience: () => any
    loadAudienceFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadAudienceSuccess: (
        audience: AudienceFixtureData,
        payload?: any
    ) => {
        audience: AudienceFixtureData
        payload?: any
    }
    setSearchTerm: (searchTerm: string) => {
        searchTerm: string
    }
    setSelectedEmail: (email: string | null) => {
        email: string | null
    }
    setShowFilter: (showFilter: AudienceShowFilter) => {
        showFilter: AudienceShowFilter
    }
    setTopicFilter: (topicFilter: AudienceTopicFilter | null) => {
        topicFilter: AudienceTopicFilter | null
    }
    trackRecipientOpened: (email: string) => {
        email: string
    }
    trackSetupViewed: () => {
        value: true
    }
    trackSnippetCopied: (variant: 'agent_prompt' | 'snippet') => {
        variant: 'agent_prompt' | 'snippet'
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface audienceLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        topics: (audience: AudienceFixtureData | null) => AudienceTopic[]
        recipients: (audience: AudienceFixtureData | null) => AudienceRecipient[]
        isSetupNeeded: (audience: AudienceFixtureData | null) => boolean | null
        filteredRecipients: (
            recipients: AudienceRecipient[],
            searchTerm: string,
            topicFilter: AudienceTopicFilter | null,
            showFilter: AudienceShowFilter
        ) => AudienceRecipient[]
        gapCounts: (audience: AudienceFixtureData | null) => AudienceGapCounts | null
        selectedRecipient: (recipients: AudienceRecipient[], selectedEmail: string | null) => AudienceRecipient | null
        selectedRecipientEvents: (
            audience: AudienceFixtureData | null,
            selectedEmail: string | null
        ) => AudienceEngagementEvent[]
    }
}

export type audienceLogicType = MakeLogicType<
    audienceLogicValues,
    audienceLogicActions,
    Record<string, any>,
    audienceLogicMeta
>

function matchesSearch(recipient: AudienceRecipient, searchTerm: string): boolean {
    const needle = searchTerm.trim().toLowerCase()
    if (!needle) {
        return true
    }
    return (
        recipient.email.includes(needle) ||
        recipient.persons.some((person) => person.name?.toLowerCase().includes(needle))
    )
}

function matchesShowFilter(recipient: AudienceRecipient, showFilter: AudienceShowFilter): boolean {
    switch (showFilter) {
        case 'suppressed':
            return recipient.suppression !== null
        case 'no_preference':
            return Object.keys(recipient.topics).length === 0
        case 'unsubscribed_all':
            return recipient.topics[ALL_MARKETING_TOPIC_ID] === 'unsubscribed'
        case 'no_person':
            return recipient.persons.length === 0
        default:
            return true
    }
}

function matchesTopicFilter(recipient: AudienceRecipient, topicFilter: AudienceTopicFilter | null): boolean {
    if (!topicFilter) {
        return true
    }
    return (recipient.topics[topicFilter.topicId] ?? 'no_preference') === topicFilter.status
}

function scenarioFromUrl(): 'empty' | 'full' {
    return router.values.searchParams.scenario === 'empty' ? 'empty' : 'full'
}

export const audienceLogic = kea<audienceLogicType>([
    path(['products', 'workflows', 'frontend', 'Audience', 'audienceLogic']),
    actions({
        setSearchTerm: (searchTerm: string) => ({ searchTerm }),
        setTopicFilter: (topicFilter: AudienceTopicFilter | null) => ({ topicFilter }),
        setShowFilter: (showFilter: AudienceShowFilter) => ({ showFilter }),
        setSelectedEmail: (email: string | null) => ({ email }),
        trackSetupViewed: true,
        trackSnippetCopied: (variant: 'snippet' | 'agent_prompt') => ({ variant }),
        trackRecipientOpened: (email: string) => ({ email }),
    }),
    loaders(() => ({
        audience: {
            __default: null as AudienceFixtureData | null,
            loadAudience: async () => {
                await new Promise((resolve) => setTimeout(resolve, 250))
                return scenarioFromUrl() === 'empty' ? EMPTY_AUDIENCE_FIXTURES : buildAudienceFixtures()
            },
        },
        createdDashboard: {
            __default: null as { id: number } | null,
            createDashboardFromTemplate: async () => {
                const dashboard = await api.create<{ id: number }>(
                    `api/environments/${ApiConfig.getCurrentTeamId()}/dashboards/create_from_template_json`,
                    { template: audienceEngagementDashboardTemplate(), creation_context: 'workflows_audience' }
                )
                // pinned: analytics event name
                posthog.capture('audience dashboard created', { dashboard_id: dashboard.id })
                router.actions.push(urls.dashboard(dashboard.id))
                return dashboard
            },
        },
    })),
    reducers({
        searchTerm: ['', { setSearchTerm: (_, { searchTerm }) => searchTerm }],
        topicFilter: [null as AudienceTopicFilter | null, { setTopicFilter: (_, { topicFilter }) => topicFilter }],
        showFilter: ['all' as AudienceShowFilter, { setShowFilter: (_, { showFilter }) => showFilter }],
        selectedEmail: [null as string | null, { setSelectedEmail: (_, { email }) => email }],
    }),
    selectors({
        topics: [
            (s) => [s.audience],
            (audience: AudienceFixtureData | null): AudienceTopic[] => audience?.topics ?? [],
        ],
        recipients: [
            (s) => [s.audience],
            (audience: AudienceFixtureData | null): AudienceRecipient[] => audience?.recipients ?? [],
        ],
        isSetupNeeded: [
            (s) => [s.audience],
            (audience: AudienceFixtureData | null): boolean | null =>
                audience === null ? null : audience.topics.length === 0 && audience.recipients.length === 0,
        ],
        filteredRecipients: [
            (s) => [s.recipients, s.searchTerm, s.topicFilter, s.showFilter],
            (
                recipients: AudienceRecipient[],
                searchTerm: string,
                topicFilter: AudienceTopicFilter | null,
                showFilter: AudienceShowFilter
            ): AudienceRecipient[] =>
                recipients.filter(
                    (recipient) =>
                        matchesSearch(recipient, searchTerm) &&
                        matchesShowFilter(recipient, showFilter) &&
                        matchesTopicFilter(recipient, topicFilter)
                ),
        ],
        recipientsPageSize: [() => [], (): number => RECIPIENTS_PAGE_SIZE],
        gapCounts: [
            (s) => [s.audience],
            (audience: AudienceFixtureData | null): AudienceGapCounts | null =>
                audience === null
                    ? null
                    : {
                          personsWithoutEmail: audience.coverage.persons_without_email,
                          personsTotal: audience.coverage.persons_total,
                          recipientsWithoutPreference: audience.recipients.filter(
                              (recipient) => Object.keys(recipient.topics).length === 0
                          ).length,
                          suppressed: audience.recipients.filter((recipient) => recipient.suppression !== null).length,
                          recipientsWithoutPerson: audience.recipients.filter(
                              (recipient) => recipient.persons.length === 0
                          ).length,
                      },
        ],
        selectedRecipient: [
            (s) => [s.recipients, s.selectedEmail],
            (recipients: AudienceRecipient[], selectedEmail: string | null): AudienceRecipient | null =>
                selectedEmail ? (recipients.find((recipient) => recipient.email === selectedEmail) ?? null) : null,
        ],
        selectedRecipientEvents: [
            (s) => [s.audience, s.selectedEmail],
            (audience: AudienceFixtureData | null, selectedEmail: string | null): AudienceEngagementEvent[] =>
                selectedEmail && audience ? audience.events.filter((event) => event.email_to === selectedEmail) : [],
        ],
    }),
    listeners(() => ({
        // pinned: analytics event names for the Audience funnel
        trackSetupViewed: () => {
            posthog.capture('audience setup viewed')
        },
        trackSnippetCopied: ({ variant }) => {
            posthog.capture('audience snippet copied', { variant })
        },
        trackRecipientOpened: ({ email }) => {
            posthog.capture('audience recipient opened', { has_email: !!email })
        },
    })),
    afterMount(({ actions }) => {
        actions.loadAudience()
    }),
])
