import { MakeLogicType, actions, afterMount, kea, listeners, path, reducers, selectors } from 'kea'
import { loaders } from 'kea-loaders'
import { router } from 'kea-router'
import posthog from 'posthog-js'

import api, { ApiConfig } from 'lib/api'
import { urls } from 'scenes/urls'

import { createFacetMatcher } from '../Workflows/WorkflowsListV2/FacetSearchBar/facetQuery'
import type { FacetDefinition, FacetSearchValue } from '../Workflows/WorkflowsListV2/FacetSearchBar/facetQuery'
import { audienceEngagementDashboardTemplate } from './audienceEngagementQueries'
import { EMPTY_AUDIENCE_FIXTURES, buildAudienceFixtures } from './audienceFixtures'
import type { AudienceEngagementEvent, AudienceFixtureData, AudienceRecipient, AudienceTopic } from './audienceFixtures'
import { buildRecipientFacets, matchesRecipientText } from './audienceRecipientFacets'

const EMPTY_SEARCH: FacetSearchValue = { filters: [], text: '' }

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface audienceLogicValues {
    audience: AudienceFixtureData | null
    audienceLoading: boolean
    createdDashboard: {
        id: number
    } | null
    createdDashboardLoading: boolean
    facets: FacetDefinition<AudienceRecipient>[]
    filteredRecipients: AudienceRecipient[]
    isSetupNeeded: boolean | null
    personsWithoutEmail: number | null
    recipients: AudienceRecipient[]
    searchValue: FacetSearchValue
    selectedEmail: string | null
    selectedRecipient: AudienceRecipient | null
    selectedRecipientEvents: AudienceEngagementEvent[]
    topics: AudienceTopic[]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface audienceLogicActions {
    clearSearch: () => {
        value: true
    }
    createDashboardFromTemplate: () => any
    createDashboardFromTemplateFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    createDashboardFromTemplateSuccess: (
        createdDashboard: {
            id: number
        },
        payload?: any
    ) => {
        createdDashboard: {
            id: number
        }
        payload?: any
    }
    loadAudience: () => any
    loadAudienceFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadAudienceSuccess: (
        audience: AudienceFixtureData,
        payload?: any
    ) => {
        audience: AudienceFixtureData
        payload?: any
    }
    setSearchValue: (searchValue: FacetSearchValue) => {
        searchValue: FacetSearchValue
    }
    setSelectedEmail: (email: string | null) => {
        email: string | null
    }
    trackRecipientOpened: (email: string) => {
        email: string
    }
    trackSetupViewed: () => {
        value: true
    }
    trackSnippetCopied: (variant: 'agent_prompt' | 'snippet') => {
        variant: 'agent_prompt' | 'snippet'
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface audienceLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        topics: (audience: AudienceFixtureData | null) => AudienceTopic[]
        recipients: (audience: AudienceFixtureData | null) => AudienceRecipient[]
        isSetupNeeded: (audience: AudienceFixtureData | null) => boolean | null
        facets: (topics: AudienceTopic[]) => FacetDefinition<AudienceRecipient>[]
        filteredRecipients: (
            recipients: AudienceRecipient[],
            searchValue: FacetSearchValue,
            facets: FacetDefinition<AudienceRecipient>[]
        ) => AudienceRecipient[]
        personsWithoutEmail: (audience: AudienceFixtureData | null) => number | null
        selectedRecipient: (recipients: AudienceRecipient[], selectedEmail: string | null) => AudienceRecipient | null
        selectedRecipientEvents: (
            audience: AudienceFixtureData | null,
            selectedEmail: string | null
        ) => AudienceEngagementEvent[]
    }
}

export type audienceLogicType = MakeLogicType<
    audienceLogicValues,
    audienceLogicActions,
    Record<string, any>,
    audienceLogicMeta
>

function scenarioFromUrl(): 'empty' | 'full' {
    return router.values.searchParams.scenario === 'empty' ? 'empty' : 'full'
}

export const audienceLogic = kea<audienceLogicType>([
    path(['products', 'workflows', 'frontend', 'Audience', 'audienceLogic']),
    actions({
        setSearchValue: (searchValue: FacetSearchValue) => ({ searchValue }),
        clearSearch: true,
        setSelectedEmail: (email: string | null) => ({ email }),
        trackSetupViewed: true,
        trackSnippetCopied: (variant: 'snippet' | 'agent_prompt') => ({ variant }),
        trackRecipientOpened: (email: string) => ({ email }),
    }),
    loaders(() => ({
        audience: {
            __default: null as AudienceFixtureData | null,
            loadAudience: async () => {
                await new Promise((resolve) => setTimeout(resolve, 250))
                return scenarioFromUrl() === 'empty' ? EMPTY_AUDIENCE_FIXTURES : buildAudienceFixtures()
            },
        },
        createdDashboard: {
            __default: null as { id: number } | null,
            createDashboardFromTemplate: async () => {
                const dashboard = await api.create<{ id: number }>(
                    `api/environments/${ApiConfig.getCurrentTeamId()}/dashboards/create_from_template_json`,
                    { template: audienceEngagementDashboardTemplate(), creation_context: 'workflows_audience' }
                )
                // pinned: analytics event name
                posthog.capture('audience dashboard created', { dashboard_id: dashboard.id })
                router.actions.push(urls.dashboard(dashboard.id))
                return dashboard
            },
        },
    })),
    reducers({
        searchValue: [
            EMPTY_SEARCH,
            { setSearchValue: (_, { searchValue }) => searchValue, clearSearch: () => EMPTY_SEARCH },
        ],
        selectedEmail: [null as string | null, { setSelectedEmail: (_, { email }) => email }],
    }),
    selectors({
        topics: [
            (s) => [s.audience],
            (audience: AudienceFixtureData | null): AudienceTopic[] => audience?.topics ?? [],
        ],
        recipients: [
            (s) => [s.audience],
            (audience: AudienceFixtureData | null): AudienceRecipient[] => audience?.recipients ?? [],
        ],
        isSetupNeeded: [
            (s) => [s.audience],
            (audience: AudienceFixtureData | null): boolean | null =>
                audience === null ? null : audience.topics.length === 0 && audience.recipients.length === 0,
        ],
        facets: [
            (s) => [s.topics],
            (topics: AudienceTopic[]): FacetDefinition<AudienceRecipient>[] => buildRecipientFacets(topics),
        ],
        filteredRecipients: [
            (s) => [s.recipients, s.searchValue, s.facets],
            (
                recipients: AudienceRecipient[],
                searchValue: FacetSearchValue,
                facets: FacetDefinition<AudienceRecipient>[]
            ): AudienceRecipient[] => recipients.filter(createFacetMatcher(searchValue, facets, matchesRecipientText)),
        ],
        personsWithoutEmail: [
            (s) => [s.audience],
            (audience: AudienceFixtureData | null): number | null => audience?.coverage.persons_without_email ?? null,
        ],
        selectedRecipient: [
            (s) => [s.recipients, s.selectedEmail],
            (recipients: AudienceRecipient[], selectedEmail: string | null): AudienceRecipient | null =>
                selectedEmail ? (recipients.find((recipient) => recipient.email === selectedEmail) ?? null) : null,
        ],
        selectedRecipientEvents: [
            (s) => [s.audience, s.selectedEmail],
            (audience: AudienceFixtureData | null, selectedEmail: string | null): AudienceEngagementEvent[] =>
                selectedEmail && audience ? audience.events.filter((event) => event.email_to === selectedEmail) : [],
        ],
    }),
    listeners(() => ({
        // pinned: analytics event names for the Audience funnel
        trackSetupViewed: () => {
            posthog.capture('audience setup viewed')
        },
        trackSnippetCopied: ({ variant }) => {
            posthog.capture('audience snippet copied', { variant })
        },
        trackRecipientOpened: ({ email }) => {
            posthog.capture('audience recipient opened', { has_email: !!email })
        },
    })),
    afterMount(({ actions }) => {
        actions.loadAudience()
    }),
])
