import {
    MakeLogicType,
    actions,
    afterMount,
    beforeUnmount,
    connect,
    kea,
    key,
    listeners,
    path,
    props,
    reducers,
    selectors,
} from 'kea'
import { loaders } from 'kea-loaders'
import { router, urlToAction } from 'kea-router'
import type { LocationChangedPayload } from 'kea-router/lib/types'
import { v5 as uuid } from 'uuid'

import api from 'lib/api'
import { TaxonomicFilterGroupType } from 'lib/components/TaxonomicFilter/types'
import { lemonToast } from 'lib/lemon-ui/LemonToast/LemonToast'
import { featureFlagLogic } from 'lib/logic/featureFlagLogic'
import { getAccessControlDisabledReason } from 'lib/utils/accessControlUtils'
import { removeProjectIdIfPresent } from 'lib/utils/kea-router'
import { tryDecodeURIComponent } from 'lib/utils/url'
import { Scene } from 'scenes/sceneTypes'
import { teamLogic } from 'scenes/teamLogic'
import { urls } from 'scenes/urls'

import { updatePropertyDefinitions } from '~/models/propertyDefinitionsModel'
import { getFilterLabel, getVirtualPropertyDefinition } from '~/taxonomy/helpers'
import {
    AccessControlLevel,
    AccessControlResourceType,
    Breadcrumb,
    Definition,
    EventDefinitionMetrics,
    ObjectMediaPreview,
    PropertyDefinition,
} from '~/types'

import {
    DistributionOffer,
    DistributionSource,
    workflowDistributionLogic,
} from 'products/workflows/frontend/Workflows/workflowDistributionLogic'

import type { SchemaEnforcementMode, UserBasicType } from '../../../types'
import type { TeamPublicType, TeamType } from '../../../types'
import { DataManagementTab } from '../DataManagementScene'
import { eventDefinitionsTableLogic } from '../events/eventDefinitionsTableLogic'
import { propertyDefinitionsTableLogic } from '../properties/propertyDefinitionsTableLogic'

export const createNewDefinition = (isEvent: boolean): Definition => ({
    id: 'new',
    name: `New ${isEvent ? 'Event' : 'Event property'}`,
    verified: false,
    hidden: false,
})

export interface SetDefinitionProps {
    merge?: boolean
}

export interface DefinitionLogicProps {
    id?: Definition['id']
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface definitionLogicValues {
    currentTeam: TeamPublicType | TeamType | null
    offers: Record<string, DistributionOffer>
    breadcrumbs: Breadcrumb[]
    definition: Definition
    definitionLoading: boolean
    definitionMissing: boolean
    definitionProjectUuid: string | null
    eventWorkflowOffer: DistributionOffer | null
    eventWorkflowOfferKey: string | null
    eventWorkflowSource: DistributionSource | null
    isEvent: boolean
    isProperty: boolean
    metrics: EventDefinitionMetrics | null
    metricsLoading: boolean
    previews: ObjectMediaPreview[]
    previewsLoading: boolean
    singular: string
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface definitionLogicActions {
    createMediaPreview: (
        uploadedMediaId: string,
        metadata?: Record<string, any>
    ) => {
        metadata: Record<string, any> | undefined
        uploadedMediaId: string
    }
    createMediaPreviewFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    createMediaPreviewSuccess: (
        previews: ObjectMediaPreview[],
        payload?: {
            metadata: Record<string, any> | undefined
            uploadedMediaId: string
        }
    ) => {
        previews: ObjectMediaPreview[]
        payload?: {
            metadata: Record<string, any> | undefined
            uploadedMediaId: string
        }
    }
    deleteDefinition: () => any
    deleteDefinitionFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    deleteDefinitionSuccess: (
        definition: Definition,
        payload?: any
    ) => {
        definition: Definition
        payload?: any
    }
    deleteMediaPreview: (previewId: string) => {
        previewId: string
    }
    deleteMediaPreviewFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    deleteMediaPreviewSuccess: (
        previews: ObjectMediaPreview[],
        payload?: {
            previewId: string
        }
    ) => {
        previews: ObjectMediaPreview[]
        payload?: {
            previewId: string
        }
    }
    dismissEventWorkflowOffer: () => {
        value: true
    }
    loadDefinition: (id: Definition['id']) => {
        id: string
    }
    loadDefinitionFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadDefinitionSuccess: (
        definition:
            | PropertyDefinition
            | {
                  created_at?: string | undefined
                  default_columns?: string[] | undefined
                  description?: string | undefined
                  enforcement_mode?: SchemaEnforcementMode | undefined
                  hidden?: boolean | undefined
                  id: string
                  is_action?: boolean | undefined
                  is_data_warehouse?: boolean | undefined
                  last_seen_at?: string | undefined
                  last_updated_at?: string | undefined
                  media_preview_urls?: string[] | undefined
                  name: string
                  owner?: UserBasicType | null | undefined
                  primary_property?: string | null | undefined
                  tags?: string[] | undefined
                  updated_at?: string | undefined
                  updated_by?: UserBasicType | null | undefined
                  verified?: boolean | undefined
                  verified_at?: string | undefined
                  verified_by?: string | undefined
              },
        payload?: {
            id: string
        }
    ) => {
        definition:
            | PropertyDefinition
            | {
                  created_at?: string | undefined
                  default_columns?: string[] | undefined
                  description?: string | undefined
                  enforcement_mode?: SchemaEnforcementMode | undefined
                  hidden?: boolean | undefined
                  id: string
                  is_action?: boolean | undefined
                  is_data_warehouse?: boolean | undefined
                  last_seen_at?: string | undefined
                  last_updated_at?: string | undefined
                  media_preview_urls?: string[] | undefined
                  name: string
                  owner?: UserBasicType | null | undefined
                  primary_property?: string | null | undefined
                  tags?: string[] | undefined
                  updated_at?: string | undefined
                  updated_by?: UserBasicType | null | undefined
                  verified?: boolean | undefined
                  verified_at?: string | undefined
                  verified_by?: string | undefined
              }
        payload?: {
            id: string
        }
    }
    loadMetrics: (id: Definition['id']) => {
        id: string
    }
    loadMetricsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadMetricsSuccess: (
        metrics: EventDefinitionMetrics | null,
        payload?: {
            id: string
        }
    ) => {
        metrics: EventDefinitionMetrics | null
        payload?: {
            id: string
        }
    }
    loadPreviews: () => {
        value: true
    }
    loadPreviewsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadPreviewsSuccess: (
        previews: ObjectMediaPreview[],
        payload?: {
            value: true
        }
    ) => {
        previews: ObjectMediaPreview[]
        payload?: {
            value: true
        }
    }
    openEventWorkflow: () => {
        value: true
    }
    refreshEventWorkflowOffer: () => {
        value: true
    }
    setDefinition: (
        definition: Partial<Definition>,
        options?: SetDefinitionProps
    ) => {
        definition: Partial<Definition>
        options: SetDefinitionProps
    }
    setDefinitionFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    setDefinitionMissing: () => {
        value: true
    }
    setDefinitionProjectUuid: (projectUuid: string | null) => {
        projectUuid: string | null
    }
    setDefinitionSuccess: (
        definition: Definition,
        payload?: {
            definition: Partial<Definition>
            options: SetDefinitionProps
        }
    ) => {
        definition: Definition
        payload?: {
            definition: Partial<Definition>
            options: SetDefinitionProps
        }
    }
    setEventWorkflowOfferKey: (contextKey: string | null) => {
        contextKey: string | null
    }
    showEventWorkflowOffer: () => {
        value: true
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface definitionLogicMeta {
    key: string
    __keaTypeGenInternalSelectorTypes: {
        eventWorkflowSource: (
            definition: Definition,
            definitionLoading: boolean,
            definitionMissing: boolean,
            isEvent: boolean,
            currentTeam: TeamPublicType | TeamType | null,
            definitionProjectUuid: string | null,
            location: {
                hash: string
                pathname: string
                search: string
            }
        ) => DistributionSource | null
        eventWorkflowOffer: (
            eventWorkflowSource: DistributionSource | null,
            eventWorkflowOfferKey: string | null,
            offers: Record<string, DistributionOffer>
        ) => DistributionOffer | null
        isEvent: (location: { hash: string; pathname: string; search: string }) => boolean
        isProperty: (isEvent: boolean) => boolean
        singular: (isEvent: boolean) => string
        breadcrumbs: (definition: Definition, isEvent: boolean) => Breadcrumb[]
    }
    __keaTypeGenInternalReducerActions: {
        'location changed (kea.router)': ({
            method,
            pathname,
            search,
            searchParams,
            hash,
            hashParams,
            initial,
            url,
            routerState,
        }: LocationChangedPayload) => {
            payload: {
                hash: string
                hashParams: Record<string, any>
                initial: boolean
                method: 'POP' | 'PUSH' | 'REPLACE'
                pathname: string
                routerState: Record<string, any>
                search: string
                searchParams: Record<string, any>
                url: string
            }
            type: 'location changed (kea.router)'
        }
    }
}

export type definitionLogicType = MakeLogicType<
    definitionLogicValues,
    definitionLogicActions,
    DefinitionLogicProps,
    definitionLogicMeta
>

// Route params arrive percent-encoded (virtual ids contain `$`); tryDecodeURIComponent keeps malformed ids
// from throwing, letting them fall through to the API's graceful 404. Both the scenes' paramsToProps and the
// component bodies must use this so the two definitionLogic build paths agree on one logic key.
export function decodeDefinitionId(id: string | undefined): string | undefined {
    return id ? tryDecodeURIComponent(id) : id
}

export const definitionLogic = kea<definitionLogicType>([
    path(['scenes', 'data-management', 'definition', 'definitionViewLogic']),
    props({} as DefinitionLogicProps),
    key((props) => props.id || 'new'),
    connect({
        values: [teamLogic, ['currentTeam'], workflowDistributionLogic, ['offers'], featureFlagLogic, []],
    }),
    actions({
        refreshEventWorkflowOffer: true,
        setEventWorkflowOfferKey: (contextKey: string | null) => ({ contextKey }),
        setDefinitionProjectUuid: (projectUuid: string | null) => ({ projectUuid }),
        showEventWorkflowOffer: true,
        openEventWorkflow: true,
        dismissEventWorkflowOffer: true,
        setDefinition: (definition: Partial<Definition>, options: SetDefinitionProps = {}) => ({ definition, options }),
        loadDefinition: (id: Definition['id']) => ({ id }),
        loadMetrics: (id: Definition['id']) => ({ id }),
        setDefinitionMissing: true,
        loadPreviews: true,
        createMediaPreview: (uploadedMediaId: string, metadata?: Record<string, any>) => ({
            uploadedMediaId,
            metadata,
        }),
        deleteMediaPreview: (previewId: string) => ({ previewId }),
    }),
    reducers(() => ({
        eventWorkflowOfferKey: [null as string | null, { setEventWorkflowOfferKey: (_, { contextKey }) => contextKey }],
        definitionProjectUuid: [
            null as string | null,
            {
                loadDefinition: () => null,
                setDefinitionProjectUuid: (_, { projectUuid }) => projectUuid,
            },
        ],
        definitionMissing: [
            false,
            {
                setDefinitionMissing: () => true,
            },
        ],
    })),
    loaders(({ values, actions }) => ({
        definition: [
            createNewDefinition(values.isEvent),
            {
                setDefinition: ({ definition, options: { merge } }) =>
                    (merge ? { ...values.definition, ...definition } : definition) as Definition,
                loadDefinition: async ({ id }, breakpoint) => {
                    const projectUuid = values.currentTeam?.uuid
                    let definition = { ...values.definition }
                    if (values.isProperty) {
                        // Virtual properties have no database row to fetch, so resolve them from the taxonomy
                        const virtualProperty = getVirtualPropertyDefinition(id)
                        if (virtualProperty) {
                            return virtualProperty.definition
                        }
                    }
                    try {
                        if (values.isEvent) {
                            // Event Definition
                            definition = await api.eventDefinitions.get({
                                eventDefinitionId: id,
                            })
                        } else {
                            // Event Property Definition
                            definition = await api.propertyDefinitions.get({
                                propertyDefinitionId: id,
                            })
                            updatePropertyDefinitions({
                                [`event/${definition.name}`]: definition as PropertyDefinition,
                            })
                        }
                        breakpoint()
                        if (projectUuid !== values.currentTeam?.uuid) {
                            throw new Error('The project changed while loading the definition')
                        }
                    } catch (response: any) {
                        actions.setDefinitionMissing()
                        throw response
                    }

                    return definition
                },
                deleteDefinition: async () => {
                    if (values.isEvent) {
                        await api.eventDefinitions.delete({ eventDefinitionId: values.definition.id })
                    } else {
                        await api.propertyDefinitions.delete({ propertyDefinitionId: values.definition.id })
                    }
                    router.actions.push(values.isEvent ? urls.eventDefinitions() : urls.propertyDefinitions())
                    if (values.isEvent) {
                        eventDefinitionsTableLogic.findMounted()?.actions.loadEventDefinitions()
                    } else {
                        propertyDefinitionsTableLogic.findMounted()?.actions.loadPropertyDefinitions()
                    }
                    return values.definition
                },
            },
        ],
        metrics: [
            null as EventDefinitionMetrics | null,
            {
                loadMetrics: async ({ id }) => {
                    if (values.isEvent) {
                        return await api.eventDefinitions.getMetrics({ eventDefinitionId: id })
                    }

                    // For properties, we currently don't have metrics in the same way as events.
                    return null
                },
            },
        ],
        previews: [
            [] as ObjectMediaPreview[],
            {
                loadPreviews: async () => {
                    if (!values.isEvent || !values.definition.id || values.definition.id === 'new') {
                        return []
                    }
                    try {
                        const response = await api.objectMediaPreviews.list(values.definition.id)
                        return response.results
                    } catch {
                        return []
                    }
                },
                createMediaPreview: async ({ uploadedMediaId, metadata }) => {
                    const preview = await api.objectMediaPreviews.create({
                        uploaded_media_id: uploadedMediaId,
                        event_definition_id: values.definition.id,
                        metadata,
                    })
                    return [preview, ...values.previews]
                },
                deleteMediaPreview: async ({ previewId }) => {
                    await api.objectMediaPreviews.delete(previewId)
                    return values.previews.filter((p) => p.id !== previewId)
                },
            },
        ],
    })),
    selectors({
        eventWorkflowSource: [
            (s) => [
                s.definition,
                s.definitionLoading,
                s.definitionMissing,
                s.isEvent,
                s.currentTeam,
                s.definitionProjectUuid,
                router.selectors.location,
            ],
            (
                definition: Definition,
                loading: boolean,
                missing: boolean,
                isEvent: boolean,
                team: TeamPublicType | TeamType | null,
                projectUuid: string | null,
                location: {
                    hash: string
                    pathname: string
                    search: string
                }
            ): DistributionSource | null => {
                if (
                    !isEvent ||
                    loading ||
                    missing ||
                    !team?.uuid ||
                    team.uuid !== projectUuid ||
                    !definition.id ||
                    definition.id === 'new' ||
                    !definition.name ||
                    definition.name.length > 400 ||
                    definition.hidden !== false ||
                    !definition.last_seen_at ||
                    removeProjectIdIfPresent(location.pathname) !== urls.eventDefinition(definition.id) ||
                    getAccessControlDisabledReason(AccessControlResourceType.Workflow, AccessControlLevel.Editor)
                ) {
                    return null
                }
                return {
                    projectUuid: team.uuid,
                    placementId: 'selected-event',
                    sourceActionId: uuid(JSON.stringify([definition.id, definition.name]), uuid.URL),
                    eligible: true,
                    trigger: {
                        type: 'event',
                        filters: { events: [{ id: definition.name, name: definition.name, type: 'events' }] },
                    },
                }
            },
        ],
        eventWorkflowOffer: [
            (s) => [s.eventWorkflowSource, s.eventWorkflowOfferKey, s.offers],
            (
                source: DistributionSource | null,
                contextKey: string | null,
                offers: Record<string, DistributionOffer>
            ): DistributionOffer | null => (source && contextKey ? (offers[contextKey] ?? null) : null),
        ],
        isEvent: [() => [router.selectors.location], ({ pathname }) => pathname.includes(urls.eventDefinitions())],
        isProperty: [(s) => [s.isEvent], (isEvent: boolean) => !isEvent],
        singular: [(s) => [s.isEvent], (isEvent: boolean): string => (isEvent ? 'event' : 'property')],
        breadcrumbs: [
            (s) => [s.definition, s.isEvent],
            (definition: Definition, isEvent: boolean): Breadcrumb[] => {
                // Resolve virtual definitions' label from the same taxonomy group the definition came from
                const propertyLabelGroup =
                    ('virtual' in definition &&
                        definition.virtual &&
                        getVirtualPropertyDefinition(definition.id)?.group) ||
                    TaxonomicFilterGroupType.EventProperties
                return [
                    {
                        key: Scene.DataManagement,
                        name: `Data management`,
                        path: isEvent ? urls.eventDefinitions() : urls.propertyDefinitions(),
                        iconType: 'event_definition',
                    },
                    {
                        key: isEvent ? DataManagementTab.EventDefinitions : DataManagementTab.PropertyDefinitions,
                        name: isEvent ? 'Events' : 'Properties',
                        path: isEvent ? urls.eventDefinitions() : urls.propertyDefinitions(),
                        iconType: isEvent ? 'event_definition' : 'property_definition',
                    },
                    {
                        key: [isEvent ? Scene.EventDefinition : Scene.PropertyDefinition, definition?.id || 'new'],
                        name:
                            definition?.id !== 'new'
                                ? getFilterLabel(
                                      definition?.name,
                                      isEvent ? TaxonomicFilterGroupType.Events : propertyLabelGroup
                                  ) || 'Untitled'
                                : 'Untitled',
                        iconType: isEvent ? 'event_definition' : 'property_definition',
                    },
                ]
            },
        ],
    }),
    listeners(({ actions, values }) => ({
        refreshEventWorkflowOffer: () => {
            if (values.eventWorkflowOfferKey) {
                workflowDistributionLogic.actions.removeOffer(values.eventWorkflowOfferKey)
            }
            actions.setEventWorkflowOfferKey(null)
            const source = values.eventWorkflowSource
            if (source) {
                workflowDistributionLogic.actions.offer(source)
                const offer = Object.values(workflowDistributionLogic.values.offers).find(
                    (offer) =>
                        offer.projectUuid === source.projectUuid &&
                        offer.placementId === 'selected-event' &&
                        JSON.stringify(offer.trigger) === JSON.stringify(source.trigger)
                )
                actions.setEventWorkflowOfferKey(offer?.contextKey ?? null)
            }
        },
        showEventWorkflowOffer: () => {
            if (values.eventWorkflowOffer) {
                workflowDistributionLogic.actions.offerShown(values.eventWorkflowOffer.contextKey)
            }
        },
        openEventWorkflow: () => {
            actions.refreshEventWorkflowOffer()
            if (
                values.eventWorkflowOffer &&
                !getAccessControlDisabledReason(AccessControlResourceType.Workflow, AccessControlLevel.Editor)
            ) {
                workflowDistributionLogic.actions.open(values.eventWorkflowOffer.contextKey)
            }
        },
        dismissEventWorkflowOffer: () => {
            if (values.eventWorkflowOffer) {
                workflowDistributionLogic.actions.dismiss(values.eventWorkflowOffer.contextKey)
            }
        },
        [featureFlagLogic.actionTypes.setFeatureFlags]: () => actions.refreshEventWorkflowOffer(),
        [teamLogic.actionTypes.loadCurrentTeamSuccess]: () => actions.refreshEventWorkflowOffer(),
        [router.actionTypes.locationChanged]: () => actions.refreshEventWorkflowOffer(),
        setDefinitionSuccess: () => actions.refreshEventWorkflowOffer(),
        loadDefinitionSuccess: () => {
            actions.setDefinitionProjectUuid(values.currentTeam?.uuid ?? null)
            actions.refreshEventWorkflowOffer()
            // Virtual definitions are taxonomy-defined and read-only, so bounce off the edit page
            if (
                'virtual' in values.definition &&
                values.definition.virtual &&
                router.values.location.pathname.endsWith('/edit')
            ) {
                router.actions.replace(urls.propertyDefinition(values.definition.id))
                return
            }
            if (values.isEvent && values.definition.id && values.definition.id !== 'new') {
                actions.loadPreviews()
            }
        },
        createMediaPreviewSuccess: () => {
            lemonToast.success('Preview image added')
        },
        createMediaPreviewFailure: () => {
            lemonToast.error('Failed to add image')
        },
        deleteMediaPreviewSuccess: () => {
            lemonToast.success('Image deleted')
        },
        deleteMediaPreviewFailure: () => {
            lemonToast.error('Failed to delete image')
        },
    })),
    // Covers client-side navigation to the edit URL while this logic is already mounted, where
    // loadDefinition (and therefore the loadDefinitionSuccess bounce above) does not re-fire
    urlToAction(({ values, props }) => ({
        [urls.propertyDefinitionEdit(':id')]: ({ id }) => {
            if (
                id &&
                decodeDefinitionId(id) === props.id &&
                'virtual' in values.definition &&
                values.definition.virtual
            ) {
                router.actions.replace(urls.propertyDefinition(values.definition.id))
            }
        },
    })),
    afterMount(({ actions, values, props }) => {
        if (!props.id || props.id === 'new') {
            actions.setDefinition(createNewDefinition(values.isEvent))
        } else {
            actions.loadDefinition(props.id)
            actions.loadMetrics(props.id)
        }
    }),
    beforeUnmount(({ values }) => {
        if (values.eventWorkflowOfferKey) {
            workflowDistributionLogic.actions.removeOffer(values.eventWorkflowOfferKey)
        }
    }),
])
