# Generated by Django 5.2.18 on 2026-10-07 16:44

import django.db.models.deletion
from django.db import migrations, models

import posthog.uuidt


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1394_backfill_secret_tokens_to_psak"),
        ("workflows", "0031_team_workflows_config_frequency_cap"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=posthog.uuidt.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("state", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("default_key", models.CharField(blank=True, max_length=32, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="posthog.team",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "default_key"),
                        name="workflow_view_team_default_key",
                    )
                ],
            },
        ),
    ]
