# Generated by Django 5.2.17 on 2026-09-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0031_team_workflows_config_frequency_cap"),
    ]

    operations = [
        migrations.AddField(
            model_name="hogflow",
            name="search_text",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
