import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, reducers, selectors } from 'kea'

import { teamLogic } from 'scenes/teamLogic'
import { urls } from 'scenes/urls'

import { osShellLogic } from '../shell/osShellLogic'
import { OS_SYSTEM_APPS, OsApp } from '../store/osAppCatalog'
import { osInstalledAppsLogic } from '../store/osInstalledAppsLogic'
import { readOsStoreMessage } from '../store/osStoreMessages'
import type { OsPoint } from '../windows/osWindowGeometry'
import { OsWindowState, osWindowsLogic } from '../windows/osWindowsLogic'
import { OS_DOCK_STORE_KEY, OsDockItem, OsDockItems, osDockClick, osDockItems } from './osDockItems'
import { osDockPinsStorageKey, readOsDockPins, writeOsDockPins } from './osDockPins'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osDockLogicValues {
    catalogApps: OsApp[] // osInstalledAppsLogic
    focusedWindow: OsWindowState | null // osWindowsLogic
    windows: OsWindowState[] // osWindowsLogic
    currentTeamId: number | null // teamLogic
    dock: OsDockItems
    knownApps: OsApp[]
    pinnedAppKeys: string[]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osDockLogicActions {
    loadCustomProducts: () => any // osInstalledAppsLogic
    openApp: (
        href: string,
        title: string,
        origin?: OsPoint | undefined,
        newWindow?: boolean | undefined
    ) => {
        href: string
        newWindow: boolean | undefined
        origin: OsPoint | undefined
        title: string
    } // osShellLogic
    closeWindow: (id: string) => {
        id: string
    } // osWindowsLogic
    focusWindow: (id: string) => {
        id: string
    } // osWindowsLogic
    minimizeWindow: (id: string) => {
        id: string
    } // osWindowsLogic
    openWindow: (
        path: string,
        options?: import('../windows/osWindowsLogic').OsOpenWindowOptions | undefined
    ) => {
        id: string
        options: import('../windows/osWindowsLogic').OsOpenWindowOptions
        path: string
    } // osWindowsLogic
    restoreWindow: (id: string) => {
        id: string
    } // osWindowsLogic
    activateItem: (
        key: string,
        origin?: OsPoint
    ) => {
        key: string
        origin: OsPoint | undefined
    }
    closeItem: (key: string) => {
        key: string
    }
    minimizeItem: (key: string) => {
        key: string
    }
    openAppStore: (origin?: OsPoint) => {
        origin: OsPoint | undefined
    }
    openItemInNewWindow: (
        key: string,
        origin?: OsPoint
    ) => {
        key: string
        origin: OsPoint | undefined
    }
    openStoreApp: (key: string) => {
        key: string
    }
    pinApp: (key: string) => {
        key: string
    }
    restoreItem: (key: string) => {
        key: string
    }
    setPinnedAppKeys: (keys: string[]) => {
        keys: string[]
    }
    unpinApp: (key: string) => {
        key: string
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osDockLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        knownApps: (catalogApps: any) => OsApp[]
        dock: (windows: any, focusedWindow: any, knownApps: any, pinnedAppKeys: any) => OsDockItems
    }
}

export type osDockLogicType = MakeLogicType<osDockLogicValues, osDockLogicActions, Record<string, any>, osDockLogicMeta>

/**
 * The dock on the OS page: the App Store, the pinned apps and the open apps. It also answers the App Store
 * window's messages, because the store runs in its own frame.
 */
export const osDockLogic = kea<osDockLogicType>([
    path(['scenes', 'os', 'dock', 'osDockLogic']),
    connect(() => ({
        values: [
            osInstalledAppsLogic,
            ['catalogApps'],
            osWindowsLogic,
            ['windows', 'focusedWindow'],
            teamLogic,
            ['currentTeamId'],
        ],
        actions: [
            osWindowsLogic,
            ['openWindow', 'focusWindow', 'minimizeWindow', 'restoreWindow', 'closeWindow'],
            osShellLogic,
            ['openApp'],
            osInstalledAppsLogic,
            ['loadCustomProducts'],
        ],
    })),
    actions({
        activateItem: (key: string, origin?: OsPoint) => ({ key, origin }),
        openAppStore: (origin?: OsPoint) => ({ origin }),
        openItemInNewWindow: (key: string, origin?: OsPoint) => ({ key, origin }),
        minimizeItem: (key: string) => ({ key }),
        restoreItem: (key: string) => ({ key }),
        closeItem: (key: string) => ({ key }),
        pinApp: (key: string) => ({ key }),
        unpinApp: (key: string) => ({ key }),
        setPinnedAppKeys: (keys: string[]) => ({ keys }),
        openStoreApp: (key: string) => ({ key }),
    }),
    reducers({
        pinnedAppKeys: [
            [] as string[],
            {
                setPinnedAppKeys: (_, { keys }) => keys,
            },
        ],
    }),
    selectors({
        knownApps: [(s) => [s.catalogApps], (catalogApps: OsApp[]): OsApp[] => [...OS_SYSTEM_APPS, ...catalogApps]],
        dock: [
            (s) => [s.windows, s.focusedWindow, s.knownApps, s.pinnedAppKeys],
            (
                windows: OsWindowState[],
                focusedWindow: OsWindowState | null,
                knownApps: OsApp[],
                pinnedAppKeys: string[]
            ): OsDockItems => osDockItems(windows, focusedWindow?.id ?? null, knownApps, pinnedAppKeys),
        ],
    }),
    listeners(({ actions, values }) => {
        const itemOf = (key: string): OsDockItem | null =>
            key === OS_DOCK_STORE_KEY
                ? values.dock.store
                : (values.dock.apps.find((item: OsDockItem) => item.key === key) ?? null)
        // In stacking order from the back, so the window that was on top ends on top again.
        const windowsOf = (item: OsDockItem): OsWindowState[] =>
            values.windows
                .filter((w: OsWindowState) => item.windowIds.includes(w.id))
                .sort((a: OsWindowState, b: OsWindowState) => a.zIndex - b.zIndex)
        const openItem = (item: OsDockItem, origin: OsPoint | undefined, newWindow: boolean): void => {
            if (item.key === OS_DOCK_STORE_KEY) {
                actions.openApp(urls.osAppStore(), 'App Store', origin, newWindow)
            } else if (item.app) {
                actions.openApp(item.app.href, item.app.name, origin, newWindow)
            } else {
                const top = windowsOf(item).pop()
                if (top) {
                    actions.openWindow(top.path, { newWindow, title: top.title, origin })
                }
            }
        }
        // Each change applies to the stored pins, so a pin made in another tab of the project is not lost.
        const savePins = (change: (keys: string[]) => string[]): void => {
            const keys = change(readOsDockPins(values.currentTeamId))
            writeOsDockPins(values.currentTeamId, keys)
            actions.setPinnedAppKeys(keys)
        }

        return {
            activateItem: ({ key, origin }) => {
                const item = itemOf(key)
                if (!item) {
                    return
                }
                const click = osDockClick(item, values.windows)
                if (click.action === 'open') {
                    openItem(item, origin, false)
                } else if (click.action === 'restore') {
                    actions.restoreWindow(click.windowId)
                } else if (click.action === 'focus') {
                    actions.focusWindow(click.windowId)
                } else {
                    actions.minimizeWindow(click.windowId)
                }
            },
            openAppStore: ({ origin }) => {
                actions.activateItem(OS_DOCK_STORE_KEY, origin)
            },
            openItemInNewWindow: ({ key, origin }) => {
                const item = itemOf(key)
                if (item) {
                    openItem(item, origin, true)
                }
            },
            minimizeItem: ({ key }) => {
                const item = itemOf(key)
                for (const w of item ? windowsOf(item) : []) {
                    if (!w.minimized) {
                        actions.minimizeWindow(w.id)
                    }
                }
            },
            restoreItem: ({ key }) => {
                const item = itemOf(key)
                for (const w of item ? windowsOf(item) : []) {
                    actions.restoreWindow(w.id)
                }
            },
            closeItem: ({ key }) => {
                const item = itemOf(key)
                for (const w of item ? windowsOf(item) : []) {
                    actions.closeWindow(w.id)
                }
            },
            pinApp: ({ key }) => {
                if (values.knownApps.some((app: OsApp) => app.key === key)) {
                    savePins((keys) => (keys.includes(key) ? keys : [...keys, key]))
                }
            },
            unpinApp: ({ key }) => {
                savePins((keys) => keys.filter((pinned) => pinned !== key))
            },
            openStoreApp: ({ key }) => {
                const app = values.knownApps.find((known: OsApp) => known.key === key)
                if (app?.href) {
                    actions.openApp(app.href, app.name)
                }
            },
        }
    }),
    afterMount(({ actions, values, cache }) => {
        actions.setPinnedAppKeys(readOsDockPins(values.currentTeamId))
        cache.disposables.add(
            () => {
                const onMessage = (event: MessageEvent): void => {
                    const message = readOsStoreMessage(event)
                    if (message?.type === 'posthog-os-store:installed-changed') {
                        actions.loadCustomProducts()
                    } else if (message?.type === 'posthog-os-store:open-app') {
                        actions.openStoreApp(message.key)
                    }
                }
                window.addEventListener('message', onMessage)
                return () => window.removeEventListener('message', onMessage)
            },
            'osStoreMessages',
            { pauseOnPageHidden: false }
        )
        // Another tab of the project can pin or unpin apps, and this dock follows it.
        cache.disposables.add(
            () => {
                const onStorage = (event: StorageEvent): void => {
                    if (event.key === osDockPinsStorageKey(values.currentTeamId)) {
                        actions.setPinnedAppKeys(readOsDockPins(values.currentTeamId))
                    }
                }
                window.addEventListener('storage', onStorage)
                return () => window.removeEventListener('storage', onStorage)
            },
            'osDockPinsSync',
            { pauseOnPageHidden: false }
        )
    }),
])
