import { MakeLogicType, connect, kea, path, selectors } from 'kea'
import { subscriptions } from 'kea-subscriptions'

import { SetupTaskId, globalSetupLogic } from 'lib/components/ProductSetup'
import { FEATURE_FLAGS } from 'lib/constants'
import { integrationsLogic } from 'lib/integrations/integrationsLogic'
import { FeatureFlagsSet, featureFlagLogic } from 'lib/logic/featureFlagLogic'

import { IntegrationType } from '~/types'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface ownSenderQuickStartLogicValues {
    ownEmailIntegrations: IntegrationType[] // integrationsLogic
    featureFlags: FeatureFlagsSet // featureFlagLogic
    ownDomainTaskDone: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface ownSenderQuickStartLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        ownDomainTaskDone: (ownEmailIntegrations: IntegrationType[], featureFlags: FeatureFlagsSet) => boolean
    }
}

export type ownSenderQuickStartLogicType = MakeLogicType<
    ownSenderQuickStartLogicValues,
    Record<string, never>,
    Record<string, any>,
    ownSenderQuickStartLogicMeta
>

export const ownSenderQuickStartLogic = kea<ownSenderQuickStartLogicType>([
    path(['products', 'workflows', 'frontend', 'Channels', 'ownSenderQuickStartLogic']),
    connect(() => ({
        values: [integrationsLogic, ['ownEmailIntegrations'], featureFlagLogic, ['featureFlags']],
    })),
    selectors({
        ownDomainTaskDone: [
            (s) => [s.ownEmailIntegrations, s.featureFlags],
            (ownEmailIntegrations: IntegrationType[], featureFlags: FeatureFlagsSet): boolean =>
                !!featureFlags[FEATURE_FLAGS.WORKFLOWS_FIRST_RUN] &&
                ownEmailIntegrations.some((sender) => sender.config?.verified === true),
        ],
    }),
    subscriptions({
        ownDomainTaskDone: (done: boolean) => {
            if (done) {
                globalSetupLogic.findMounted()?.actions.markTaskAsCompleted(SetupTaskId.SendFromOwnEmailDomain)
            }
        },
    }),
])
