import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, reducers, selectors } from 'kea'

import { CommandOpenSource, commandLogic } from 'lib/components/Command/commandLogic'

import { AppsItemGroup, groupApps } from '~/layout/panel-layout/navbar/tabs/appsCatalog'
import { navAppsTabLogic } from '~/layout/panel-layout/navbar/tabs/navAppsTabLogic'
import { FileSystemImport } from '~/queries/schema/schema-general'

import { osShellLogic } from '../../shell/osShellLogic'
import { OsWindowState, osWindowsLogic } from '../../windows/osWindowsLogic'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osLauncherLogicValues {
    allItems: FileSystemImport[] // navAppsTabLogic
    focusedWindow: OsWindowState | null // osWindowsLogic
    windows: OsWindowState[] // osWindowsLogic
    groupedApps: AppsItemGroup[]
    search: string
    spotlightOpen: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osLauncherLogicActions {
    closeCommand: () => { value: true } // commandLogic
    toggleCommand: (source: CommandOpenSource) => { source: CommandOpenSource } // commandLogic
    maximizeWindow: (id: string) => { id: string } // osWindowsLogic
    minimizeWindow: (id: string) => { id: string } // osWindowsLogic
    openWindow: (
        path: string,
        options?: import('../../windows/osWindowsLogic').OsOpenWindowOptions
    ) => { id: string; options: import('../../windows/osWindowsLogic').OsOpenWindowOptions; path: string } // osWindowsLogic
    restoreWindow: (id: string) => { id: string } // osWindowsLogic
    openApp: (
        href: string,
        title: string,
        origin?: import('../../windows/osWindowGeometry').OsPoint
    ) => { href: string; origin: import('../../windows/osWindowGeometry').OsPoint | undefined; title: string } // osShellLogic
    goHome: () => { value: true }
    maximizeVisible: () => { value: true }
    setSearch: (search: string) => { search: string }
    setSpotlightOpen: (open: boolean) => { open: boolean }
}

export type osLauncherLogicType = MakeLogicType<osLauncherLogicValues, osLauncherLogicActions, Record<string, any>>

export const osLauncherLogic = kea<osLauncherLogicType>([
    path(['scenes', 'os', 'variants', 'launcher', 'osLauncherLogic']),
    connect(() => ({
        values: [navAppsTabLogic, ['allItems'], osWindowsLogic, ['windows', 'focusedWindow']],
        actions: [
            osWindowsLogic,
            ['openWindow', 'maximizeWindow', 'minimizeWindow', 'restoreWindow'],
            osShellLogic,
            ['openApp'],
            commandLogic,
            ['toggleCommand', 'closeCommand'],
        ],
    })),
    actions({
        setSearch: (search: string) => ({ search }),
        setSpotlightOpen: (open: boolean) => ({ open }),
        goHome: true,
        maximizeVisible: true,
    }),
    reducers({
        search: ['', { setSearch: (_, { search }) => search, openApp: () => '' }],
        spotlightOpen: [false, { setSpotlightOpen: (_, { open }) => open, openApp: () => false }],
    }),
    selectors({
        groupedApps: [
            (s) => [s.allItems, s.search],
            (allItems: FileSystemImport[], search: string): AppsItemGroup[] => groupApps(allItems, search),
        ],
    }),
    listeners(({ actions, values }) => ({
        // Cmd+K opens the launcher in place of the command palette, which stays one click away in its apps.
        toggleCommand: ({ source }) => {
            if (source === 'keyboard-shortcut') {
                actions.closeCommand()
                actions.setSpotlightOpen(!values.spotlightOpen)
            }
        },
        openWindow: () => actions.maximizeVisible(),
        restoreWindow: () => actions.maximizeVisible(),
        maximizeVisible: () => {
            for (const w of values.windows) {
                if (!w.minimized && !w.maximized) {
                    actions.maximizeWindow(w.id)
                }
            }
        },
        goHome: () => {
            for (const w of values.windows) {
                if (!w.minimized) {
                    actions.minimizeWindow(w.id)
                }
            }
        },
    })),
    afterMount(({ actions }) => actions.maximizeVisible()),
])
