import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, reducers, selectors } from 'kea'
import { router } from 'kea-router'
import type { LocationChangedPayload } from 'kea-router/lib/types'

import { removeProjectIdIfPresent } from 'lib/utils/kea-router'
import { sceneLogic } from 'scenes/sceneLogic'
import { Scene, SceneConfig } from 'scenes/sceneTypes'

import { FlatNavProductGroup, flatNavLogic } from '~/layout/panel-layout/navbar/tabs/flat-nav/flatNavLogic'
import { customProductsLogic } from '~/layout/panel-layout/ProjectTree/customProductsLogic'

import { osFrameSrc } from '../bridge/osFrame'
import { osAppSrc } from './osAppSrc'
import { OsDesktopColumns, osDesktopColumns } from './osDesktopApps'
import { OsWallpaperKey, OsWallpaperOption, resolveOsWallpaper } from './osWallpapers'

export interface OsShellWindow {
    /** Null while the window shows the page URL, whose title comes from the scene. */
    title: string | null
    /** A same-origin path, see `osFrameSrc`. */
    src: string
}

export interface OsFocusedWindow {
    title: string
    src: string
}

function samePage(a: string, b: string): boolean {
    return (
        removeProjectIdIfPresent(new URL(a, 'http://x').pathname) ===
        removeProjectIdIfPresent(new URL(b, 'http://x').pathname)
    )
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osShellLogicValues {
    productGroups: FlatNavProductGroup[] // flatNavLogic
    activeSceneId: string | null // sceneLogic
    sceneConfig: SceneConfig | null // sceneLogic
    desktopColumns: OsDesktopColumns
    focusedWindow: OsFocusedWindow | null
    openedWindow: OsShellWindow | null
    storedWallpaper: string | null
    wallpaper: OsWallpaperOption
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osShellLogicActions {
    loadCustomProducts: () => any // customProductsLogic
    locationChanged: ({
        method,
        pathname,
        search,
        searchParams,
        hash,
        hashParams,
        initial,
        url,
        routerState,
    }: LocationChangedPayload) => {
        hash: string
        hashParams: Record<string, any>
        initial: boolean
        method: 'POP' | 'PUSH' | 'REPLACE'
        pathname: string
        routerState: Record<string, any>
        search: string
        searchParams: Record<string, any>
        url: string
    } // router
    openApp: (
        href: string,
        title: string
    ) => {
        src: string | null
        title: string
    }
    setWallpaper: (wallpaper: OsWallpaperKey) => {
        wallpaper: OsWallpaperKey
    }
    showPage: (src: string | null) => {
        src: string | null
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osShellLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        wallpaper: (storedWallpaper: string | null) => OsWallpaperOption
        desktopColumns: (productGroups: FlatNavProductGroup[]) => OsDesktopColumns
        focusedWindow: (
            openedWindow: OsShellWindow | null,
            activeSceneId: string | null,
            sceneConfig: SceneConfig | null
        ) => OsFocusedWindow | null
    }
}

export type osShellLogicType = MakeLogicType<
    osShellLogicValues,
    osShellLogicActions,
    Record<string, any>,
    osShellLogicMeta
>

export const osShellLogic = kea<osShellLogicType>([
    path(['scenes', 'os', 'shell', 'osShellLogic']),
    connect(() => ({
        values: [flatNavLogic, ['productGroups'], sceneLogic, ['activeSceneId', 'sceneConfig']],
        actions: [customProductsLogic, ['loadCustomProducts'], router, ['locationChanged']],
    })),
    actions({
        setWallpaper: (wallpaper: OsWallpaperKey) => ({ wallpaper }),
        openApp: (href: string, title: string) => ({ src: osAppSrc(href, window.location.origin), title }),
        showPage: (src: string | null) => ({ src }),
    }),
    reducers({
        // Holds whatever was saved, so a wallpaper that no longer exists still resolves to a real one.
        storedWallpaper: [
            null as string | null,
            { persist: true },
            {
                setWallpaper: (_, { wallpaper }) => wallpaper,
            },
        ],
        openedWindow: [
            null as OsShellWindow | null,
            {
                openApp: (state, { src, title }) => (src ? { src, title } : state),
                showPage: (_, { src }) => (src ? { src, title: null } : null),
            },
        ],
    }),
    selectors({
        wallpaper: [
            (s) => [s.storedWallpaper],
            (storedWallpaper: string | null): OsWallpaperOption => resolveOsWallpaper(storedWallpaper),
        ],
        desktopColumns: [
            (s) => [s.productGroups],
            (productGroups: FlatNavProductGroup[]): OsDesktopColumns => osDesktopColumns(productGroups),
        ],
        focusedWindow: [
            (s) => [s.openedWindow, s.activeSceneId, s.sceneConfig],
            (
                openedWindow: OsShellWindow | null,
                activeSceneId: string | null,
                sceneConfig: SceneConfig | null
            ): OsFocusedWindow | null => {
                if (!openedWindow) {
                    return null
                }
                if (openedWindow.title) {
                    return { title: openedWindow.title, src: openedWindow.src }
                }
                // `/os` is the empty desktop, so the page URL opens no window there.
                if (activeSceneId === Scene.Os) {
                    return null
                }
                return { ...openedWindow, title: sceneConfig?.name ?? 'PostHog' }
            },
        ],
    }),
    listeners(({ actions, values }) => ({
        // The command palette, notifications, account links and back and forward all change the page
        // URL. The window follows, so those links open where the user looks.
        locationChanged: () => {
            const src = osFrameSrc(router.values.location, window.location.origin)
            // A redirect that only adds the project id to the same page must not reload the window.
            if (src && values.openedWindow && samePage(src, values.openedWindow.src)) {
                return
            }
            actions.showPage(src)
        },
    })),
    afterMount(({ actions, cache }) => {
        actions.showPage(osFrameSrc(router.values.location, window.location.origin))
        // Settings in a window can change the picked tools, so the desktop reloads them when the
        // user comes back to it.
        cache.disposables.add(
            () => {
                const onFocus = (): void => actions.loadCustomProducts()
                window.addEventListener('focus', onFocus)
                return () => window.removeEventListener('focus', onFocus)
            },
            'reloadToolsOnFocus',
            { pauseOnPageHidden: false }
        )
    }),
])
