import { MakeLogicType, actions, afterMount, connect, kea, path, reducers, selectors } from 'kea'
import { router } from 'kea-router'

import { sceneLogic } from 'scenes/sceneLogic'
import { Scene, SceneConfig } from 'scenes/sceneTypes'

import { FlatNavProductGroup, flatNavLogic } from '~/layout/panel-layout/navbar/tabs/flat-nav/flatNavLogic'

import { osFrameSrc } from '../bridge/osFrame'
import { OsDesktopColumns, osDesktopColumns } from './osDesktopApps'
import { OsWallpaperKey, OsWallpaperOption, resolveOsWallpaper } from './osWallpapers'

export interface OsShellWindow {
    title: string
    /** A same-origin path, see `osFrameSrc`. */
    src: string
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osShellLogicValues {
    productGroups: FlatNavProductGroup[] // flatNavLogic
    activeSceneId: string | null // sceneLogic
    sceneConfig: SceneConfig | null // sceneLogic
    desktopColumns: OsDesktopColumns
    focusedWindow: OsShellWindow | null
    openedApp: OsShellWindow | null
    pageSrc: string | null
    storedWallpaper: string | null
    wallpaper: OsWallpaperOption
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osShellLogicActions {
    openApp: (
        href: string,
        title: string
    ) => {
        href: string
        title: string
    }
    setPageSrc: (src: string | null) => {
        src: string | null
    }
    setWallpaper: (wallpaper: OsWallpaperKey) => {
        wallpaper: OsWallpaperKey
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osShellLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        wallpaper: (storedWallpaper: string | null) => OsWallpaperOption
        desktopColumns: (productGroups: FlatNavProductGroup[]) => OsDesktopColumns
        focusedWindow: (
            openedApp: OsShellWindow | null,
            pageSrc: string | null,
            activeSceneId: string | null,
            sceneConfig: SceneConfig | null
        ) => OsShellWindow | null
    }
}

export type osShellLogicType = MakeLogicType<
    osShellLogicValues,
    osShellLogicActions,
    Record<string, any>,
    osShellLogicMeta
>

export const osShellLogic = kea<osShellLogicType>([
    path(['scenes', 'os', 'shell', 'osShellLogic']),
    connect(() => ({
        values: [flatNavLogic, ['productGroups'], sceneLogic, ['activeSceneId', 'sceneConfig']],
    })),
    actions({
        setWallpaper: (wallpaper: OsWallpaperKey) => ({ wallpaper }),
        openApp: (href: string, title: string) => ({ href, title }),
        setPageSrc: (src: string | null) => ({ src }),
    }),
    reducers({
        // Holds whatever was saved, so a wallpaper that no longer exists still resolves to a real one.
        storedWallpaper: [
            null as string | null,
            { persist: true },
            {
                setWallpaper: (_, { wallpaper }) => wallpaper,
            },
        ],
        openedApp: [
            null as OsShellWindow | null,
            {
                openApp: (_, { href, title }) => {
                    const url = new URL(href, window.location.origin)
                    const src = osFrameSrc(url, window.location.origin)
                    return src ? { title, src } : null
                },
            },
        ],
        // The URL the page opened on. Later changes to the page URL must not reload the window.
        pageSrc: [
            null as string | null,
            {
                setPageSrc: (_, { src }) => src,
            },
        ],
    }),
    selectors({
        wallpaper: [
            (s) => [s.storedWallpaper],
            (storedWallpaper: string | null): OsWallpaperOption => resolveOsWallpaper(storedWallpaper),
        ],
        desktopColumns: [
            (s) => [s.productGroups],
            (productGroups: FlatNavProductGroup[]): OsDesktopColumns => osDesktopColumns(productGroups),
        ],
        focusedWindow: [
            (s) => [s.openedApp, s.pageSrc, s.activeSceneId, s.sceneConfig],
            (
                openedApp: OsShellWindow | null,
                pageSrc: string | null,
                activeSceneId: string | null,
                sceneConfig: SceneConfig | null
            ): OsShellWindow | null => {
                if (openedApp) {
                    return openedApp
                }
                // `/os` is the empty desktop, so it opens no window.
                if (!pageSrc || activeSceneId === Scene.Os) {
                    return null
                }
                return { title: sceneConfig?.name ?? 'PostHog', src: pageSrc }
            },
        ],
    }),
    afterMount(({ actions }) => {
        actions.setPageSrc(osFrameSrc(router.values.location, window.location.origin))
    }),
])
